# 파일

참고자료
- https://wikidocs.net/14593

## open()

파일은 open() 명령에서 `<MODE>` 값에 따라 읽고 쓴다. [Python builtin functions](https://docs.python.org/3/library/functions.html)
    
>open(file, mode='rb', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
  - mode는 파일에 대한 액션과 파일 형식을 지정한다: rb, wb, rt, wt
     - 액션 : w(기록), a(추가), r(읽기:기본값)
     - 타입 : t(텍스트:기본값), b(2진 파일)
open 으로 열린 객체는 `.close()` 로 닫아 주어야 한다.

file:
- Text file: 문자코드(ascii code (를 기반으로 한)), ipynb도 text파일임
- Binary file: byte streams(바이트 단위로 저장되어 있음, 이미지 등)

### 읽기 모드

`read()` 함수: 파일의 내용 전체를 문자열로 리턴한다.

In [5]:
%pwd

'C:\\Users\\SBAuser\\Jupyter_Python\\week2'

In [6]:
%ls

 C 드라이브의 볼륨: Windows
 볼륨 일련 번호: 8EF6-8BCC

 C:\Users\SBAuser\Jupyter_Python\week2 디렉터리

2022-11-16  오전 10:06    <DIR>          .
2022-11-16  오전 10:00    <DIR>          ..
2022-11-16  오전 10:00    <DIR>          .ipynb_checkpoints
2022-11-16  오전 10:06            38,686 1-17File-0.ipynb
2022-11-16  오전 10:00                 0 Count_Word.ipynb
2022-11-16  오전 10:00                56 even_number.txt
2022-11-16  오전 10:00                25 odd_number.txt
2022-11-16  오전 10:00                55 odd_number1.txt
2022-11-16  오전 10:00                55 odd_number2.txt
2022-11-16  오전 10:00                55 odd_number정답.txt
2022-11-16  오전 10:00            23,103 Q-Guess_Number(random).ipynb
2022-11-16  오전 10:00             3,137 Q-sequence실습.ipynb
2022-11-16  오전 10:05                 0 test.txt
2022-11-16  오전 10:00               153 testwrite.txt
2022-11-16  오전 10:00           116,369 WEEK1-RE.ipynb
              12개 파일             181,694 바이트
               3개 디렉터리  416,366,112,768 바이트 남음

In [15]:
# 파일 열기 (open)
f = open("test.txt", "w", encoding="utf8") # 현재 디렉터리에 쓰기모드로, 유니코드 텍스트 저장되는 파일을 열겠다! / 뭐썼다가 닫고 이걸로 다시 열면 파일 내용 다 사라짐.

In [3]:
f

In [3]:
type(f)

_io.TextIOWrapper

파일 입출력 관련 주요 함수 시도해보기

In [4]:
f.name

'test.txt'

In [5]:
f.mode

'w'

In [8]:
f.encoding

'utf8'

In [18]:
size = f.write("Life is too short\n") # \n > 줄바꿈 / 파일에다가 씀

In [10]:
size

18

In [11]:
len("Life is too short\n")

18

In [19]:
print(f"{size} 만큼 기록:")
size = f.write("You need Python.\n")
print("{size} 만큼 기록:") # 앞에 f 안들어가서 그러는듯

18 만큼 기록:
{size} 만큼 기록:

In [20]:
f.close() # 사용후 반드시 닫는다.

읽기 모드로 텍스트 불러오면 파일 전체를 읽어온다 -> 파일이 클 경우 문제 발생 가능

In [27]:
f = open("test.txt", "rt", encoding="utf8") # text파일을 읽겠다

In [17]:
f.name

'test.txt'

In [18]:
f.encoding

'utf8'

In [19]:
f.mode

'rt'

In [20]:
text = f.read() # EOF = end of file
print("READ:", text)

READ: Life is too short
You need Python.

In [28]:
text = f.read(10) # EOF = end of file / n개의 개수 만큼 읽는거 >> n개의 개수 만큼 --> offset
print("READ:", text)

READ: Life is to

In [29]:
text = f.read(10) # EOF = end of file / n개의 개수 만큼 읽는거 >> n개의 개수 만큼 --> offset
print("READ:", text)

READ: o short
Li

In [30]:
f.tell() # 파일 포인터 위치 조회

21

In [24]:
# 또 읽으면 내용x >> 더 읽을게 없는거!

text = f.read() 
print("READ:", text)

READ: fe is too short
Life is too short
You need Python.

In [25]:
# 또 읽으면 내용x >> 더 읽을게 없는거!

text = f.read() 
print("READ:", text)

READ:

In [31]:
f.close()

In [44]:
f = open("test.txt", "rt", encoding="utf8") # text파일을 읽겠다

In [46]:
# 한 글자씩 읽기 

text = f.read(1) 
print("READ:", text)

READ: i

In [47]:
f.close()

In [39]:
# f = open("1-05Sequence_0.ipynb", "rt", encoding="utf8") # 경로 정확치 않아서 그럼

FileNotFoundError: [Errno 2] No such file or directory: '1-05Sequence_0.ipynb'

In [51]:
f = open("WEEK1-RE.ipynb", "rt", encoding="utf8")

In [52]:
f.name

'WEEK1-RE.ipynb'

In [53]:
f.mode, f.name, f.encoding

('rt', 'WEEK1-RE.ipynb', 'utf8')

In [54]:
f.close()

`readline()` 함수 이용하기

파일이 클 경우, 라인 단위로 파일을 읽는 것이 효율적
- 읽기 함수: f.read([size]) 문자 수 만큼 / f.readline([size]) 몇 줄.. 라인 수 만큼 / f.readlines([size]) 전체 라인을 리스트로 반환

위키백가 화이트스페이스 보기

In [57]:
f = open("test.txt", "rt", encoding="utf8")
while True:
    line = f.readline() # --> EOL \n \r\n EOF 힌줄씩 읽히는거..? 라인단위로 보고싶으면 이걸로!
    if not line: # 공백이 오지 않을때까지 읽는거임
        break
    line = line.strip() # 공백 문자 제거(strip 왼쪽, 오른쪽 공백 지움..)
    print(line)

f.close()

Life is too short
You need Python.

In [32]:
f = open("WEEK1-RE.ipynb", "rt", encoding="utf8")
while True:
    line = f.readline() # --> EOL \n \r\n EOF 힌줄씩 읽히는거..? 라인단위로 보고싶으면 이걸로!
    if not line: # 공백이 오지 않을때까지 읽는거임
        break
    line = line.strip() # 공백 문자 제거(strip 왼쪽, 오른쪽 양쪽 공백 지움..)
    print(line)

f.close()

{
"cells": [
{
"cell_type": "markdown",
"id": "62e7155d-2c2b-44ca-bc38-78493efe82e9",
"metadata": {},
"source": [
"# code block"
]
},
{
"cell_type": "code",
"execution_count": null,
"id": "ea2d1946-ba70-4d68-a240-50c392bd60ba",
"metadata": {},
"outputs": [],
"source": [
"# 코드블럭.\n",
"\n",
"class a {\n",
"    \n",
"    \n",
"} "
]
},
{
"cell_type": "markdown",
"id": "f31be0f5-a687-4c4b-b961-f4519d878717",
"metadata": {},
"source": [
"Indentation, not braces\n",
"\n",
"```python\n",
"for x in array:\n",
"    if x < pivot:\n",
"        less.append(x)\n",
"    else:\n",
"        greater.append(x)\n",
"```"
]
},
{
"cell_type": "code",
"execution_count": 6,
"id": "535b6314-b6a5-4e9d-bfec-27c25656b4b7",
"metadata": {},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"1\n",
"2\n",
"1\n",
"2\n",
"1\n",
"2\n",
"1\n",
"2\n",
"200\n",
"10000\n"
]
}
],
"source": [
"for x in [1,2,3,4] :  # code blocks\n",
"    if x < 10:\n",
"        pass\n",
"    if x < 5 :\n",
"        print(1)\n",
"        print(2)\n",
"        \n",
"        \n",
"print(200)\n",
"print(10000)"
]
},
{
"cell_type": "markdown",
"id": "5be4be4e-85ef-4a7a-bcf9-c2477572782c",
"metadata": {},
"source": [
"\n",
"## [표현식과 구문]\n",
"\n",
"- 표현식은 실제 실행되어 하나의 값으로 처리하는 구문\n",
"- 구문(statements)이란 프로그램 언어에서 특정한 로직을 처리해서 상태를 처리하는 구문\n",
"- 보통 표현식을 처리한 후에 문장에 저장해서 처리\n"
]
},
{
"cell_type": "markdown",
"id": "6a152d3a-2abb-461a-9cb6-4732869487a7",
"metadata": {},
"source": [
"#### 대입문\n",
"\n",
"- 특정 표현식/리터럴을 변수 등에 저장하는 연산자\n",
"- 대입문 `=` 연산자로 지정한다"
]
},
{
"cell_type": "markdown",
"id": "849ea00c-b06d-4f77-907b-ad676711d7eb",
"metadata": {},
"source": [
"변수 --> 객체 (Object)"
]
},
{
"cell_type": "code",
"execution_count": 2,
"id": "5084c0f7-1b11-46b2-b263-e3f49756c45d",
"metadata": {},
"outputs": [],
"source": [
"variable = 1000  # 표현식!!!(제일 간단한 표현식! > 변수에 값을 대입, 대입 연산을 통해서 변수에 스칼라 값 1000을 대입)"
]
},
{
"cell_type": "markdown",
"id": "ec2b9376-b427-40e8-bd58-17478602fee2",
"metadata": {},
"source": [
"### 리터럴"
]
},
{
"cell_type": "code",
"execution_count": 7,
"id": "d3e09bcc-9e0d-46e2-8230-12f8d618fe10",
"metadata": {},
"outputs": [],
"source": [
"variable = 1000 # 숫자 리터럴"
]
},
{
"cell_type": "code",
"execution_count": 2,
"id": "37bee75f-a903-4d7b-8fb4-891fe0af1d6a",
"metadata": {},
"outputs": [],
"source": [
"variable = '안녕하세요' # 문자 리터럴"
]
},
{
"cell_type": "code",
"execution_count": 4,
"id": "3913f0df-c5d6-46b1-b7c6-63b8eb3e8ef6",
"metadata": {},
"outputs": [],
"source": [
"obj =  variable # 객체를 표현하는 리터럴(객체 안에 속성, 함수, 메소드가 포함된게 객체!)"
]
},
{
"cell_type": "markdown",
"id": "12a43f8b-c121-4d68-9e10-78817df328cf",
"metadata": {},
"source": [
"### 객체와 연산\n",
"- 객체: method + attributes\n",
"- `.` 을 통해 접근 가능"
]
},
{
"cell_type": "code",
"execution_count": 5,
"id": "43c89cbe-3409-41a8-b4ef-24e28394bc00",
"metadata": {},
"outputs": [],
"source": [
"obj = 1"
]
},
{
"cell_type": "code",
"execution_count": 6,
"id": "594eb622-119c-44a8-9cb5-b13436e2bac2",
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"int"
]
},
"execution_count": 6,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"# class 속성\n",
"obj.__class__"
]
},
{
"cell_type": "code",
"execution_count": 5,
"id": "8d74edbf-1f1b-4774-b723-4d6993cd63b6",
"metadata": {},
"outputs": [],
"source": [
"variable = 1000"
]
},
{
"cell_type": "code",
"execution_count": 6,
"id": "a62e712a-26bb-4bf5-9681-2646a808158b",
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"1001"
]
},
"execution_count": 6,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"variable + 1"
]
},
{
"cell_type": "code",
"execution_count": 7,
"id": "e8694a18-d08d-4585-b568-0027663f3203",
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"2000"
]
},
"execution_count": 7,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"variable + variable"
]
},
{
"cell_type": "code",
"execution_count": 8,
"id": "4323cc09-8375-45f1-a8f5-57ac4d3a23a4",
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"'안녕하세요 쥬피터 노트북'"
]
},
"execution_count": 8,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"obj = \"안녕하세요\" + ' 쥬피터 노트북'\n",
"obj"
]
},
{
"cell_type": "code",
"execution_count": 9,
"id": "c0428109-3811-407a-8b94-f302b8803559",
"metadata": {},
"outputs": [
{
"ename": "TypeError",
"evalue": "can only concatenate str (not \"int\") to str",
"output_type": "error",
"traceback": [
"\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
"\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
"Cell \u001b[0;32mIn [9], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mobj\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m1\u001b[39;49m\n",
"\u001b[0;31mTypeError\u001b[0m: can only concatenate str (not \"int\") to str"
]
}
],
"source": [
"obj + 1 # 다른 데이터와 연산은x"
]
},
{
"cell_type": "code",
"execution_count": 10,
"id": "a148790b-6e5c-4b62-9e48-5567177aaa50",
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"'안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북'"
]
},
"execution_count": 10,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"obj + obj"
]
},
{
"cell_type": "code",
"execution_count": 11,
"id": "72a5831b-6dca-47a3-a1a9-50453314263e",
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"'안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북'"
]
},
"execution_count": 11,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"obj * 10"
]
},
{
"cell_type": "markdown",
"id": "063c0bed-ad7a-48f3-a8e7-d77201e88d98",
"metadata": {
"tags": []
},
"source": [
"## 주석\n",
"\n",
"```python\n",
"results = []\n",
"for line in file_handle:\n",
"    # keep the empty lines for now\n",
"    # if len(line) == 0:\n",
"    #   continue\n",
"    results.append(line.replace('foo', 'bar'))\n",
" ```"
]
},
{
"cell_type": "code",
"execution_count": 103,
"id": "d658083c-06ea-49fa-84da-a41baf6613c3",
"metadata": {},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"hello\n"
]
}
],
"source": [
"print(\n",
"    # comment\n",
"    # comment\n",
"    # comment\n",
"    \n",
"    \"hello\"    # 10000 번째 에러가 발생!\n",
")"
]
},
{
"cell_type": "code",
"execution_count": 8,
"id": "57df6f2f-fb0f-409d-b02a-0a4318893294",
"metadata": {},
"outputs": [
{
"ename": "SyntaxError",
"evalue": "invalid syntax (672102624.py, line 4)",
"output_type": "error",
"traceback": [
"\u001b[1;36m  Cell \u001b[1;32mIn [8], line 4\u001b[1;36m\u001b[0m\n\u001b[1;33m    3,4,5,6)\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
]
}
],
"source": [
"print(\n",
"    1,\n",
"    2\n",
"    3,4,5,6)\n",
"\n",
"# error난거 잘 보고 고치기"
]
},
{
"cell_type": "markdown",
"id": "d15920b3-4d4d-4aa8-9e68-a90b665ca1e1",
"metadata": {},
"source": [
"## 예약어\n",
"- 대소문자 구분 O"
]
},
{
"cell_type": "code",
"execution_count": 147,
"id": "f33b2102-3f81-4380-ad1e-34ac8cf15d88",
"metadata": {},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"예약어 목록: ['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']\n",
"예약어 갯수: 36\n"
]
}
],
"source": [
"import keyword\n",
"\n",
"print(\"예약어 목록:\", keyword.kwlist)\n",
"print(\"예약어 갯수:\", len(keyword.kwlist))"
]
},
{
"cell_type": "code",
"execution_count": 9,
"id": "c26592e2-e560-4ce3-8172-30f5d00348f3",
"metadata": {},
"outputs": [
{
"ename": "SyntaxError",
"evalue": "cannot assign to False (1429262388.py, line 1)",
"output_type": "error",
"traceback": [
"\u001b[1;36m  Cell \u001b[1;32mIn [9], line 1\u001b[1;36m\u001b[0m\n\u001b[1;33m    False = 1\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m cannot assign to False\n"
]
}
],
"source": [
"False = 1"
]
},
{
"cell_type": "code",
"execution_count": 10,
"id": "b3c8a3ae-c342-4a41-8616-f0591f09dd8e",
"metadata": {},
"outputs": [],
"source": [
"false = 1"
]
},
{
"cell_type": "markdown",
"id": "eae12273-9f62-45fb-8eb6-80702cd518b3",
"metadata": {},
"source": [
"## 객체 식별자\n",
"\n",
" - 프로그램을 작성할 때 특정 값을 보관하는 영역을 지정 \n",
" - 예약어를 제외한 이름으로 지정\n",
" - 숫자로 시작할 수 없다\n",
" - 변수는 문자, 숫자, `_`로 구성 (대쉬 - (x))\n",
" - 첫글자는 문자와 `_` 만 올 수 있다."
]
},
{
"cell_type": "markdown",
"id": "ccc438f3-6758-4002-8456-310ead8fe949",
"metadata": {},
"source": [
"**파이썬 커뮤니티는 이름을 다음 같이 권장**:\n",
"\n",
"- 함수, 메서드, 속성은 under_lower 같이 선언.\n",
"- 상수는 under_lower 혹은 대문자 - ALL_CAPS(일반적으로 상수는 다 대문자로! 가독성 good)\n",
"- 클래스는 캠멜 형태 - ThisIsClass \n",
"- 애트리뷰트 - interface, _internal, __private\n"
]
},
{
"attachments": {
"9391263b-51eb-469f-8e2b-417d62e8ef98.png": {

In [33]:
f = open("WEEK1-RE.ipynb", "rt", encoding="utf8")
while True:
    line = f.readline(10) # --> EOL \n \r\n EOF 까지 힌줄씩 읽히는거..? 라인단위로 보고싶으면 이걸로!
    # debugging!!! >> 정보를 한줄씩 출력해보면서 보는 과정이 다 디버깅 과정임! --> line by line
    print(type(line), len(line))
    if not line: 
        break
    line = line.strip() 
    print(line)

f.close()

<class 'str'> 2
{
<class 'str'> 10
"cells":
<class 'str'> 2
[
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "mar
<class 'str'> 8
kdown",
<class 'str'> 10
"id": "
<class 'str'> 10
62e7155d-2
<class 'str'> 10
c2b-44ca-b
<class 'str'> 10
c38-78493e
<class 'str'> 9
fe82e9",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"# cod
<class 'str'> 9
e block"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 8
: null,
<class 'str'> 10
"id": "
<class 'str'> 10
ea2d1946-b
<class 'str'> 10
a70-4d68-a
<class 'str'> 10
240-50c392
<class 'str'> 9
bd60ba",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 8
s": [],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"# 코드블
<class 'str'> 7
럭.\n",
<class 'str'> 10
"\n",
<class 'str'> 10
"class
<class 'str'> 9
a {\n",
<class 'str'> 10
"    \
<class 'str'> 4
n",
<class 'str'> 10
"    \
<class 'str'> 4
n",
<class 'str'> 9
"} "
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "mar
<class 'str'> 8
kdown",
<class 'str'> 10
"id": "
<class 'str'> 10
f31be0f5-a
<class 'str'> 10
687-4c4b-b
<class 'str'> 10
961-f4519d
<class 'str'> 9
878717",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"Inden
<class 'str'> 10
tation, no
<class 'str'> 10
t braces\n
<class 'str'> 3
",
<class 'str'> 10
"\n",
<class 'str'> 10
"```py
<class 'str'> 9
thon\n",
<class 'str'> 10
"for x
<class 'str'> 10
in array:
<class 'str'> 5
\n",
<class 'str'> 10
"    i
<class 'str'> 10
f x < pivo
<class 'str'> 7
t:\n",
<class 'str'> 10
"
<class 'str'> 10
less.ap
<class 'str'> 10
pend(x)\n"
<class 'str'> 2
,
<class 'str'> 10
"    e
<class 'str'> 9
lse:\n",
<class 'str'> 10
"
<class 'str'> 10
greater
<class 'str'> 10
.append(x)
<class 'str'> 5
\n",
<class 'str'> 10
"```"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 5
: 6,
<class 'str'> 10
"id": "
<class 'str'> 10
535b6314-b
<class 'str'> 10
6a5-4e9d-b
<class 'str'> 10
fec-27c256
<class 'str'> 9
56b4b7",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 6
s": [
<class 'str'> 6
{
<class 'str'> 10
"name
<class 'str'> 10
": "stdout
<class 'str'> 3
",
<class 'str'> 10
"outp
<class 'str'> 10
ut_type":
<class 'str'> 10
"stream",
<class 'str'> 10
"text
<class 'str'> 5
": [
<class 'str'> 10
"1\n
<class 'str'> 3
",
<class 'str'> 10
"2\n
<class 'str'> 3
",
<class 'str'> 10
"1\n
<class 'str'> 3
",
<class 'str'> 10
"2\n
<class 'str'> 3
",
<class 'str'> 10
"1\n
<class 'str'> 3
",
<class 'str'> 10
"2\n
<class 'str'> 3
",
<class 'str'> 10
"1\n
<class 'str'> 3
",
<class 'str'> 10
"2\n
<class 'str'> 3
",
<class 'str'> 10
"200
<class 'str'> 5
\n",
<class 'str'> 10
"100
<class 'str'> 6
00\n"
<class 'str'> 7
]
<class 'str'> 6
}
<class 'str'> 6
],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"for x
<class 'str'> 10
in [1,2,3
<class 'str'> 10
,4] :  # c
<class 'str'> 10
ode blocks
<class 'str'> 5
\n",
<class 'str'> 10
"    i
<class 'str'> 10
f x < 10:\
<class 'str'> 4
n",
<class 'str'> 10
"
<class 'str'> 10
pass\n"
<class 'str'> 2
,
<class 'str'> 10
"    i
<class 'str'> 10
f x < 5 :\
<class 'str'> 4
n",
<class 'str'> 10
"
<class 'str'> 10
print(1
<class 'str'> 6
)\n",
<class 'str'> 10
"
<class 'str'> 10
print(2
<class 'str'> 6
)\n",
<class 'str'> 10
"
<class 'str'> 8
\n",
<class 'str'> 10
"
<class 'str'> 8
\n",
<class 'str'> 10
"print
<class 'str'> 10
(200)\n",
<class 'str'> 10
"print
<class 'str'> 9
(10000)"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "mar
<class 'str'> 8
kdown",
<class 'str'> 10
"id": "
<class 'str'> 10
5be4be4e-8
<class 'str'> 10
5ef-4a7a-b
<class 'str'> 10
cf9-c24775
<class 'str'> 9
72782c",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"\n",
<class 'str'> 10
"## [표
<class 'str'> 10
현식과 구문]\n"
<class 'str'> 2
,
<class 'str'> 10
"\n",
<class 'str'> 10
"- 표현식
<class 'str'> 10
은 실제 실행되어
<class 'str'> 10
하나의 값으로 처리
<class 'str'> 10
하는 구문\n",
<class 'str'> 10
"- 구문(
<class 'str'> 10
statements
<class 'str'> 10
)이란 프로그램 언
<class 'str'> 10
어에서 특정한 로직
<class 'str'> 10
을 처리해서 상태를
<class 'str'> 10
처리하는 구문\n
<class 'str'> 3
",
<class 'str'> 10
"- 보통
<class 'str'> 10
표현식을 처리한 후
<class 'str'> 10
에 문장에 저장해서
<class 'str'> 7
처리\n"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "mar
<class 'str'> 8
kdown",
<class 'str'> 10
"id": "
<class 'str'> 10
6a152d3a-2
<class 'str'> 10
abb-461a-9
<class 'str'> 10
cb6-473286
<class 'str'> 9
9487a7",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"####
<class 'str'> 8
대입문\n",
<class 'str'> 10
"\n",
<class 'str'> 10
"- 특정
<class 'str'> 10
표현식/리터럴을 변
<class 'str'> 10
수 등에 저장하는
<class 'str'> 8
연산자\n",
<class 'str'> 10
"- 대입문
<class 'str'> 10
`=` 연산자로
<class 'str'> 6
지정한다"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "mar
<class 'str'> 8
kdown",
<class 'str'> 10
"id": "
<class 'str'> 10
849ea00c-b
<class 'str'> 10
06d-4f77-9
<class 'str'> 10
07b-ad6767
<class 'str'> 9
11d7eb",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"변수 --
<class 'str'> 10
> 객체 (Obje
<class 'str'> 5
ct)"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 5
: 2,
<class 'str'> 10
"id": "
<class 'str'> 10
5084c0f7-1
<class 'str'> 10
b11-46b2-b
<class 'str'> 10
263-e3f497
<class 'str'> 9
56c45d",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 8
s": [],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"varia
<class 'str'> 10
ble = 1000
<class 'str'> 10
# 표현식!!!
<class 'str'> 10
(제일 간단한 표현
<class 'str'> 10
식! > 변수에 값
<class 'str'> 10
을 대입, 대입 연
<class 'str'> 10
산을 통해서 변수에
<class 'str'> 10
스칼라 값 100
<class 'str'> 8
0을 대입)"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "mar
<class 'str'> 8
kdown",
<class 'str'> 10
"id": "
<class 'str'> 10
ec2b9376-b
<class 'str'> 10
427-40e8-b
<class 'str'> 10
d58-174786
<class 'str'> 9
02fee2",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"### 리
<class 'str'> 4
터럴"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 5
: 7,
<class 'str'> 10
"id": "
<class 'str'> 10
d3e09bcc-9
<class 'str'> 10
e0d-46e2-8
<class 'str'> 10
230-12f8d6
<class 'str'> 9
18fe10",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 8
s": [],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"varia
<class 'str'> 10
ble = 1000
<class 'str'> 10
# 숫자 리터럴"
<class 'str'> 1

<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 5
: 2,
<class 'str'> 10
"id": "
<class 'str'> 10
37bee75f-a
<class 'str'> 10
903-4d7b-8
<class 'str'> 10
fb4-891fe0
<class 'str'> 9
af1d6a",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 8
s": [],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"varia
<class 'str'> 10
ble = '안녕하
<class 'str'> 10
세요' # 문자 리
<class 'str'> 4
터럴"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 5
: 4,
<class 'str'> 10
"id": "
<class 'str'> 10
3913f0df-c
<class 'str'> 10
5d6-46b1-b
<class 'str'> 10
7c6-63b8eb
<class 'str'> 9
3e8ef6",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 8
s": [],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"obj =
<class 'str'> 10
variable
<class 'str'> 10
# 객체를 표현하
<class 'str'> 10
는 리터럴(객체 안
<class 'str'> 10
에 속성, 함수,
<class 'str'> 10
메소드가 포함된게
<class 'str'> 6
객체!)"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "mar
<class 'str'> 8
kdown",
<class 'str'> 10
"id": "
<class 'str'> 10
12a43f8b-c
<class 'str'> 10
121-4d68-9
<class 'str'> 10
e10-78817d
<class 'str'> 9
f328cf",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"### 객
<class 'str'> 10
체와 연산\n",
<class 'str'> 10
"- 객체:
<class 'str'> 10
method +
<class 'str'> 10
attributes
<class 'str'> 5
\n",
<class 'str'> 10
"- `.`
<class 'str'> 10
을 통해 접근 가
<class 'str'> 3
능"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 5
: 5,
<class 'str'> 10
"id": "
<class 'str'> 10
43c89cbe-3
<class 'str'> 10
409-41a8-b
<class 'str'> 10
4ef-24e283
<class 'str'> 9
94bc00",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 8
s": [],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"obj =
<class 'str'> 4
1"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 5
: 6,
<class 'str'> 10
"id": "
<class 'str'> 10
594eb622-1
<class 'str'> 10
19c-44a8-9
<class 'str'> 10
cb5-b13436
<class 'str'> 9
e2bac2",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 6
s": [
<class 'str'> 6
{
<class 'str'> 10
"data
<class 'str'> 5
": {
<class 'str'> 10
"tex
<class 'str'> 10
t/plain":
<class 'str'> 2
[
<class 'str'> 10
"in
<class 'str'> 3
t"
<class 'str'> 8
]
<class 'str'> 8
},
<class 'str'> 10
"exec
<class 'str'> 10
ution_coun
<class 'str'> 7
t": 6,
<class 'str'> 10
"meta
<class 'str'> 10
data": {},
<class 'str'> 1

<class 'str'> 10
"outp
<class 'str'> 10
ut_type":
<class 'str'> 10
"execute_r
<class 'str'> 7
esult"
<class 'str'> 6
}
<class 'str'> 6
],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"# cla
<class 'str'> 10
ss 속성\n",
<class 'str'> 10
"obj._
<class 'str'> 10
_class__"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 5
: 5,
<class 'str'> 10
"id": "
<class 'str'> 10
8d74edbf-1
<class 'str'> 10
f1b-4774-b
<class 'str'> 10
723-4d6993
<class 'str'> 9
cd63b6",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 8
s": [],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"varia
<class 'str'> 10
ble = 1000
<class 'str'> 2
"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 5
: 6,
<class 'str'> 10
"id": "
<class 'str'> 10
a62e712a-2
<class 'str'> 10
6bb-4bf5-9
<class 'str'> 10
681-2646a8
<class 'str'> 9
08158b",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 6
s": [
<class 'str'> 6
{
<class 'str'> 10
"data
<class 'str'> 5
": {
<class 'str'> 10
"tex
<class 'str'> 10
t/plain":
<class 'str'> 2
[
<class 'str'> 10
"10
<class 'str'> 4
01"
<class 'str'> 8
]
<class 'str'> 8
},
<class 'str'> 10
"exec
<class 'str'> 10
ution_coun
<class 'str'> 7
t": 6,
<class 'str'> 10
"meta
<class 'str'> 10
data": {},
<class 'str'> 1

<class 'str'> 10
"outp
<class 'str'> 10
ut_type":
<class 'str'> 10
"execute_r
<class 'str'> 7
esult"
<class 'str'> 6
}
<class 'str'> 6
],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"varia
<class 'str'> 9
ble + 1"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 5
: 7,
<class 'str'> 10
"id": "
<class 'str'> 10
e8694a18-d
<class 'str'> 10
08d-4585-b
<class 'str'> 10
568-002766
<class 'str'> 9
3f3203",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 6
s": [
<class 'str'> 6
{
<class 'str'> 10
"data
<class 'str'> 5
": {
<class 'str'> 10
"tex
<class 'str'> 10
t/plain":
<class 'str'> 2
[
<class 'str'> 10
"20
<class 'str'> 4
00"
<class 'str'> 8
]
<class 'str'> 8
},
<class 'str'> 10
"exec
<class 'str'> 10
ution_coun
<class 'str'> 7
t": 7,
<class 'str'> 10
"meta
<class 'str'> 10
data": {},
<class 'str'> 1

<class 'str'> 10
"outp
<class 'str'> 10
ut_type":
<class 'str'> 10
"execute_r
<class 'str'> 7
esult"
<class 'str'> 6
}
<class 'str'> 6
],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"varia
<class 'str'> 10
ble + vari
<class 'str'> 6
able"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 5
: 8,
<class 'str'> 10
"id": "
<class 'str'> 10
4323cc09-8
<class 'str'> 10
375-45f1-a
<class 'str'> 10
8f5-57ac4d
<class 'str'> 9
3a23a4",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 6
s": [
<class 'str'> 6
{
<class 'str'> 10
"data
<class 'str'> 5
": {
<class 'str'> 10
"tex
<class 'str'> 10
t/plain":
<class 'str'> 2
[
<class 'str'> 10
"'안
<class 'str'> 10
녕하세요 쥬피터 노
<class 'str'> 5
트북'"
<class 'str'> 8
]
<class 'str'> 8
},
<class 'str'> 10
"exec
<class 'str'> 10
ution_coun
<class 'str'> 7
t": 8,
<class 'str'> 10
"meta
<class 'str'> 10
data": {},
<class 'str'> 1

<class 'str'> 10
"outp
<class 'str'> 10
ut_type":
<class 'str'> 10
"execute_r
<class 'str'> 7
esult"
<class 'str'> 6
}
<class 'str'> 6
],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"obj =
<class 'str'> 10
\"안녕하세요\"
<class 'str'> 10
+ ' 쥬피터 노
<class 'str'> 8
트북'\n",
<class 'str'> 10
"obj"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 5
: 9,
<class 'str'> 10
"id": "
<class 'str'> 10
c0428109-3
<class 'str'> 10
811-407a-8
<class 'str'> 10
b94-f302b8
<class 'str'> 9
803559",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 6
s": [
<class 'str'> 6
{
<class 'str'> 10
"enam
<class 'str'> 10
e": "TypeE
<class 'str'> 7
rror",
<class 'str'> 10
"eval
<class 'str'> 10
ue": "can
<class 'str'> 10
only conca
<class 'str'> 10
tenate str
<class 'str'> 10
(not \"in
<class 'str'> 10
t\") to st
<class 'str'> 4
r",
<class 'str'> 10
"outp
<class 'str'> 10
ut_type":
<class 'str'> 9
"error",
<class 'str'> 10
"trac
<class 'str'> 10
eback": [
<class 'str'> 10
"\u0
<class 'str'> 10
01b[0;31m-
<class 'str'> 10
----------
<class 'str'> 10
----------
<class 'str'> 10
----------
<class 'str'> 10
----------
<class 'str'> 10
----------
<class 'str'> 10
----------
<class 'str'> 10
----------
<class 'str'> 10
----\u001b
<class 'str'> 6
[0m",
<class 'str'> 10
"\u0
<class 'str'> 10
01b[0;31mT
<class 'str'> 10
ypeError\u
<class 'str'> 10
001b[0m
<class 'str'> 10

<class 'str'> 10

<class 'str'> 10

<class 'str'> 10
Traceback
<class 'str'> 10
(most rece
<class 'str'> 10
nt call la
<class 'str'> 6
st)",
<class 'str'> 10
"Cel
<class 'str'> 10
l \u001b[0
<class 'str'> 10
;32mIn [9]
<class 'str'> 10
, line 1\u
<class 'str'> 10
001b[0m\n\
<class 'str'> 10
u001b[0;32
<class 'str'> 10
m----> 1\u
<class 'str'> 10
001b[0m \u
<class 'str'> 10
001b[43mob
<class 'str'> 10
j\u001b[49
<class 'str'> 10
m\u001b[43
<class 'str'> 10
m \u001b[4
<class 'str'> 10
9m\u001b[3
<class 'str'> 10
8;5;241;43
<class 'str'> 10
m+\u001b[3
<class 'str'> 10
9;49m\u001
<class 'str'> 10
b[43m \u00
<class 'str'> 10
1b[49m\u00
<class 'str'> 10
1b[38;5;24
<class 'str'> 10
1;43m1\u00
<class 'str'> 10
1b[39;49m\
<class 'str'> 4
n",
<class 'str'> 10
"\u0
<class 'str'> 10
01b[0;31mT
<class 'str'> 10
ypeError\u
<class 'str'> 10
001b[0m: c
<class 'str'> 10
an only co
<class 'str'> 10
ncatenate
<class 'str'> 10
str (not \
<class 'str'> 10
"int\") to
<class 'str'> 6
str"
<class 'str'> 7
]
<class 'str'> 6
}
<class 'str'> 6
],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"obj +
<class 'str'> 10
1 # 다른 데이
<class 'str'> 9
터와 연산은x"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 6
: 10,
<class 'str'> 10
"id": "
<class 'str'> 10
a148790b-6
<class 'str'> 10
e5c-4b62-9
<class 'str'> 10
e48-556717
<class 'str'> 9
7aaa50",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 6
s": [
<class 'str'> 6
{
<class 'str'> 10
"data
<class 'str'> 5
": {
<class 'str'> 10
"tex
<class 'str'> 10
t/plain":
<class 'str'> 2
[
<class 'str'> 10
"'안
<class 'str'> 10
녕하세요 쥬피터 노
<class 'str'> 10
트북안녕하세요 쥬피
<class 'str'> 8
터 노트북'"
<class 'str'> 8
]
<class 'str'> 8
},
<class 'str'> 10
"exec
<class 'str'> 10
ution_coun
<class 'str'> 8
t": 10,
<class 'str'> 10
"meta
<class 'str'> 10
data": {},
<class 'str'> 1

<class 'str'> 10
"outp
<class 'str'> 10
ut_type":
<class 'str'> 10
"execute_r
<class 'str'> 7
esult"
<class 'str'> 6
}
<class 'str'> 6
],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"obj +
<class 'str'> 6
obj"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "cod
<class 'str'> 4
e",
<class 'str'> 10
"execut
<class 'str'> 10
ion_count"
<class 'str'> 6
: 11,
<class 'str'> 10
"id": "
<class 'str'> 10
72a5831b-6
<class 'str'> 10
dca-47a3-a
<class 'str'> 10
1a9-504533
<class 'str'> 9
14263e",
<class 'str'> 10
"metada
<class 'str'> 9
ta": {},
<class 'str'> 10
"output
<class 'str'> 6
s": [
<class 'str'> 6
{
<class 'str'> 10
"data
<class 'str'> 5
": {
<class 'str'> 10
"tex
<class 'str'> 10
t/plain":
<class 'str'> 2
[
<class 'str'> 10
"'안
<class 'str'> 10
녕하세요 쥬피터 노
<class 'str'> 10
트북안녕하세요 쥬피
<class 'str'> 10
터 노트북안녕하세요
<class 'str'> 10
쥬피터 노트북안녕
<class 'str'> 10
하세요 쥬피터 노트
<class 'str'> 10
북안녕하세요 쥬피터
<class 'str'> 10
노트북안녕하세요
<class 'str'> 10
쥬피터 노트북안녕하
<class 'str'> 10
세요 쥬피터 노트북
<class 'str'> 10
안녕하세요 쥬피터
<class 'str'> 10
노트북안녕하세요 쥬
<class 'str'> 10
피터 노트북안녕하세
<class 'str'> 10
요 쥬피터 노트북'
<class 'str'> 2
"
<class 'str'> 8
]
<class 'str'> 8
},
<class 'str'> 10
"exec
<class 'str'> 10
ution_coun
<class 'str'> 8
t": 11,
<class 'str'> 10
"meta
<class 'str'> 10
data": {},
<class 'str'> 1

<class 'str'> 10
"outp
<class 'str'> 10
ut_type":
<class 'str'> 10
"execute_r
<class 'str'> 7
esult"
<class 'str'> 6
}
<class 'str'> 6
],
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"obj *
<class 'str'> 5
10"
<class 'str'> 5
]
<class 'str'> 5
},
<class 'str'> 4
{
<class 'str'> 10
"cell_t
<class 'str'> 10
ype": "mar
<class 'str'> 8
kdown",
<class 'str'> 10
"id": "
<class 'str'> 10
063c0bed-a
<class 'str'> 10
d7a-48f3-a
<class 'str'> 10
8e7-d77201
<class 'str'> 9
e88d98",
<class 'str'> 10
"metada
<class 'str'> 7
ta": {
<class 'str'> 10
"tags"
<class 'str'> 5
: []
<class 'str'> 6
},
<class 'str'> 10
"source
<class 'str'> 5
": [
<class 'str'> 10
"## 주석
<class 'str'> 5
\n",
<class 'str'> 10
"\n",
<class 'str'> 10

In [34]:
f = open("WEEK1-RE.ipynb", "rt", encoding="utf8")
while True:
    line = f.read(100) # 100자 읽기
    # debugging!!! >> 정보를 한줄씩 출력(print)해보면서 보는 과정이 다 디버깅 과정임! --> line by line
    print(type(line), len(line))
    if not line: 
        break
    line = line.strip() 
    print(line)

f.close()

<class 'str'> 100
{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "62e7155d-2c2b-44ca-bc38-78493efe82e9",
   "m
<class 'str'> 100
etadata": {},
   "source": [
    "# code block"
   ]
  },
  {
   "cell_type": "code",
   "execution_
<class 'str'> 100
count": null,
   "id": "ea2d1946-ba70-4d68-a240-50c392bd60ba",
   "metadata": {},
   "outputs": [],
<class 'str'> 100
"source": [
    "# 코드블럭.\n",
    "\n",
    "class a {\n",
    "    \n",
    "    \n",
    "} "
<class 'str'> 100
]
  },
  {
   "cell_type": "markdown",
   "id": "f31be0f5-a687-4c4b-b961-f4519d878717",
   "metadat
<class 'str'> 100
a": {},
   "source": [
    "Indentation, not braces\n",
    "\n",
    "```python\n",
    "for x in a
<class 'str'> 100
rray:\n",
    "    if x < pivot:\n",
    "        less.append(x)\n",
    "    else:\n",
    "
<class 'str'> 100
greater.append(x)\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "
<class 'str'> 100
id": "535b6314-b6a5-4e9d-bfec-27c25656b4b7",
   "metadata": {},
   "outputs": [
    {
     "name": "
<class 'str'> 100
stdout",
     "output_type": "stream",
     "text": [
      "1\n",
      "2\n",
      "1\n",
      "
<class 'str'> 100
2\n",
      "1\n",
      "2\n",
      "1\n",
      "2\n",
      "200\n",
      "10000\n"
     ]
<class 'str'> 100
}
   ],
   "source": [
    "for x in [1,2,3,4] :  # code blocks\n",
    "    if x < 10:\n",
    "
<class 'str'> 100
pass\n",
    "    if x < 5 :\n",
    "        print(1)\n",
    "        print(2)\n",
    "
<class 'str'> 100
\n",
    "        \n",
    "print(200)\n",
    "print(10000)"
   ]
  },
  {
   "cell_type": "mark
<class 'str'> 100
down",
   "id": "5be4be4e-85ef-4a7a-bcf9-c2477572782c",
   "metadata": {},
   "source": [
    "\n",
<class 'str'> 100
"## [표현식과 구문]\n",
    "\n",
    "- 표현식은 실제 실행되어 하나의 값으로 처리하는 구문\n",
    "- 구문(statements)이란 프로그램
<class 'str'> 100
언어에서 특정한 로직을 처리해서 상태를 처리하는 구문\n",
    "- 보통 표현식을 처리한 후에 문장에 저장해서 처리\n"
   ]
  },
  {
   "cell_type"
<class 'str'> 100
: "markdown",
   "id": "6a152d3a-2abb-461a-9cb6-4732869487a7",
   "metadata": {},
   "source": [
<class 'str'> 100
"#### 대입문\n",
    "\n",
    "- 특정 표현식/리터럴을 변수 등에 저장하는 연산자\n",
    "- 대입문 `=` 연산자로 지정한다"
   ]
  },
<class 'str'> 100
{
   "cell_type": "markdown",
   "id": "849ea00c-b06d-4f77-907b-ad676711d7eb",
   "metadata": {},
<class 'str'> 100
"source": [
    "변수 --> 객체 (Object)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2
<class 'str'> 100
,
   "id": "5084c0f7-1b11-46b2-b263-e3f49756c45d",
   "metadata": {},
   "outputs": [],
   "source":
<class 'str'> 100
[
    "variable = 1000  # 표현식!!!(제일 간단한 표현식! > 변수에 값을 대입, 대입 연산을 통해서 변수에 스칼라 값 1000을 대입)"
   ]
  },
<class 'str'> 100
{
   "cell_type": "markdown",
   "id": "ec2b9376-b427-40e8-bd58-17478602fee2",
   "metadata": {},
<class 'str'> 100
"source": [
    "### 리터럴"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id"
<class 'str'> 100
: "d3e09bcc-9e0d-46e2-8230-12f8d618fe10",
   "metadata": {},
   "outputs": [],
   "source": [
    "v
<class 'str'> 100
ariable = 1000 # 숫자 리터럴"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "37
<class 'str'> 100
bee75f-a903-4d7b-8fb4-891fe0af1d6a",
   "metadata": {},
   "outputs": [],
   "source": [
    "variab
<class 'str'> 100
le = '안녕하세요' # 문자 리터럴"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "3913
<class 'str'> 100
f0df-c5d6-46b1-b7c6-63b8eb3e8ef6",
   "metadata": {},
   "outputs": [],
   "source": [
    "obj =  v
<class 'str'> 100
ariable # 객체를 표현하는 리터럴(객체 안에 속성, 함수, 메소드가 포함된게 객체!)"
   ]
  },
  {
   "cell_type": "markdown",
   "i
<class 'str'> 100
d": "12a43f8b-c121-4d68-9e10-78817df328cf",
   "metadata": {},
   "source": [
    "### 객체와 연산\n",
<class 'str'> 100
"- 객체: method + attributes\n",
    "- `.` 을 통해 접근 가능"
   ]
  },
  {
   "cell_type": "code",
   "ex
<class 'str'> 100
ecution_count": 5,
   "id": "43c89cbe-3409-41a8-b4ef-24e28394bc00",
   "metadata": {},
   "outputs":
<class 'str'> 100
[],
   "source": [
    "obj = 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
<class 'str'> 100
"id": "594eb622-119c-44a8-9cb5-b13436e2bac2",
   "metadata": {},
   "outputs": [
    {
     "data":
<class 'str'> 100
{
      "text/plain": [
       "int"
      ]
     },
     "execution_count": 6,
     "metadata": {},
<class 'str'> 100
"output_type": "execute_result"
    }
   ],
   "source": [
    "# class 속성\n",
    "obj.__clas
<class 'str'> 100
s__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "8d74edbf-1f1b-4774-b72
<class 'str'> 100
3-4d6993cd63b6",
   "metadata": {},
   "outputs": [],
   "source": [
    "variable = 1000"
   ]
  },
<class 'str'> 100
{
   "cell_type": "code",
   "execution_count": 6,
   "id": "a62e712a-26bb-4bf5-9681-2646a808158b
<class 'str'> 100
",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1001"
<class 'str'> 100
]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
<class 'str'> 100
}
   ],
   "source": [
    "variable + 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count"
<class 'str'> 100
: 7,
   "id": "e8694a18-d08d-4585-b568-0027663f3203",
   "metadata": {},
   "outputs": [
    {
<class 'str'> 100
"data": {
      "text/plain": [
       "2000"
      ]
     },
     "execution_count": 7,
     "metad
<class 'str'> 100
ata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "variable + variable"
<class 'str'> 100
]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "4323cc09-8375-45f1-a8f5-57a
<class 'str'> 100
c4d3a23a4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'안
<class 'str'> 100
녕하세요 쥬피터 노트북'"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "
<class 'str'> 100
execute_result"
    }
   ],
   "source": [
    "obj = \"안녕하세요\" + ' 쥬피터 노트북'\n",
    "obj"
   ]
  },
<class 'str'> 100
{
   "cell_type": "code",
   "execution_count": 9,
   "id": "c0428109-3811-407a-8b94-f302b8803559
<class 'str'> 100
",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "can only conc
<class 'str'> 100
atenate str (not \"int\") to str",
     "output_type": "error",
     "traceback": [
      "\u001b[0;
<class 'str'> 100
31m---------------------------------------------------------------------------\u001b[0m",
      "\u0
<class 'str'> 100
01b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
<class 'str'> 100
"Cell \u001b[0;32mIn [9], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mobj\u001b[49m\u0
<class 'str'> 100
01b[43m \u001b[49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m1\u001b[3
<class 'str'> 100
9;49m\n",
      "\u001b[0;31mTypeError\u001b[0m: can only concatenate str (not \"int\") to str"
<class 'str'> 100
]
    }
   ],
   "source": [
    "obj + 1 # 다른 데이터와 연산은x"
   ]
  },
  {
   "cell_type": "code",
<class 'str'> 100
"execution_count": 10,
   "id": "a148790b-6e5c-4b62-9e48-5567177aaa50",
   "metadata": {},
   "outpu
<class 'str'> 100
ts": [
    {
     "data": {
      "text/plain": [
       "'안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북'"
      ]
<class 'str'> 100
},
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ]
<class 'str'> 100
,
   "source": [
    "obj + obj"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
<class 'str'> 100
"id": "72a5831b-6dca-47a3-a1a9-50453314263e",
   "metadata": {},
   "outputs": [
    {
     "data":
<class 'str'> 100
{
      "text/plain": [
       "'안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕
<class 'str'> 100
하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북안녕하세요 쥬피터 노트북'"
      ]
     },
     "execution_co
<class 'str'> 100
unt": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "
<class 'str'> 100
obj * 10"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "063c0bed-ad7a-48f3-a8e7-d77201e88d98",
<class 'str'> 100
"metadata": {
    "tags": []
   },
   "source": [
    "## 주석\n",
    "\n",
    "```python\n",
<class 'str'> 100
"results = []\n",
    "for line in file_handle:\n",
    "    # keep the empty lines for now\n",
<class 'str'> 100
"    # if len(line) == 0:\n",
    "    #   continue\n",
    "    results.append(line.replace('foo'
<class 'str'> 100
, 'bar'))\n",
    " ```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "id": "
<class 'str'> 100
d658083c-06ea-49fa-84da-a41baf6613c3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout
<class 'str'> 100
",
     "output_type": "stream",
     "text": [
      "hello\n"
     ]
    }
   ],
   "source": [
<class 'str'> 100
"print(\n",
    "    # comment\n",
    "    # comment\n",
    "    # comment\n",
    "    \n",
<class 'str'> 100
"    \"hello\"    # 10000 번째 에러가 발생!\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "executio
<class 'str'> 100
n_count": 8,
   "id": "57df6f2f-fb0f-409d-b02a-0a4318893294",
   "metadata": {},
   "outputs": [
<class 'str'> 100
{
     "ename": "SyntaxError",
     "evalue": "invalid syntax (672102624.py, line 4)",
     "output
<class 'str'> 100
_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn [8], line 4\u001b[1;36
<class 'str'> 100
m\u001b[0m\n\u001b[1;33m    3,4,5,6)\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u
<class 'str'> 100
001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "print(\n",
<class 'str'> 100
"    1,\n",
    "    2\n",
    "    3,4,5,6)\n",
    "\n",
    "# error난거 잘 보고 고치기"
   ]
  },
  {
<class 'str'> 100
"cell_type": "markdown",
   "id": "d15920b3-4d4d-4aa8-9e68-a90b665ca1e1",
   "metadata": {},
   "
<class 'str'> 100
source": [
    "## 예약어\n",
    "- 대소문자 구분 O"
   ]
  },
  {
   "cell_type": "code",
   "execution_cou
<class 'str'> 100
nt": 147,
   "id": "f33b2102-3f81-4380-ad1e-34ac8cf15d88",
   "metadata": {},
   "outputs": [
    {
<class 'str'> 100
"name": "stdout",
     "output_type": "stream",
     "text": [
      "예약어 목록: ['False', 'None',
<class 'str'> 100
'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'd
<class 'str'> 100
ef', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is'
<class 'str'> 100
, 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']\n",
<class 'str'> 100
"예약어 갯수: 36\n"
     ]
    }
   ],
   "source": [
    "import keyword\n",
    "\n",
    "print
<class 'str'> 100
(\"예약어 목록:\", keyword.kwlist)\n",
    "print(\"예약어 갯수:\", len(keyword.kwlist))"
   ]
  },
  {
   "ce
<class 'str'> 100
ll_type": "code",
   "execution_count": 9,
   "id": "c26592e2-e560-4ce3-8172-30f5d00348f3",
   "meta
<class 'str'> 100
data": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "cannot assign to False
<class 'str'> 100
(1429262388.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cel
<class 'str'> 100
l \u001b[1;32mIn [9], line 1\u001b[1;36m\u001b[0m\n\u001b[1;33m    False = 1\u001b[0m\n\u001b[1;37m
<class 'str'> 100
^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m cannot assign to False\n"
<class 'str'> 100
]
    }
   ],
   "source": [
    "False = 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_co
<class 'str'> 100
unt": 10,
   "id": "b3c8a3ae-c342-4a41-8616-f0591f09dd8e",
   "metadata": {},
   "outputs": [],
   "
<class 'str'> 100
source": [
    "false = 1"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eae12273-9f62-45fb-8e
<class 'str'> 100
b6-80702cd518b3",
   "metadata": {},
   "source": [
    "## 객체 식별자\n",
    "\n",
    " - 프로그램을 작성할 때
<class 'str'> 100
특정 값을 보관하는 영역을 지정 \n",
    " - 예약어를 제외한 이름으로 지정\n",
    " - 숫자로 시작할 수 없다\n",
    " - 변수는 문자, 숫자, `_
<class 'str'> 100
`로 구성 (대쉬 - (x))\n",
    " - 첫글자는 문자와 `_` 만 올 수 있다."
   ]
  },
  {
   "cell_type": "markdown",
   "i
<class 'str'> 100
d": "ccc438f3-6758-4002-8456-310ead8fe949",
   "metadata": {},
   "source": [
    "**파이썬 커뮤니티는 이름을 다
<class 'str'> 100
음 같이 권장**:\n",
    "\n",
    "- 함수, 메서드, 속성은 under_lower 같이 선언.\n",
    "- 상수는 under_lower 혹은 대문자 -
<class 'str'> 100
ALL_CAPS(일반적으로 상수는 다 대문자로! 가독성 good)\n",
    "- 클래스는 캠멜 형태 - ThisIsClass \n",
    "- 애트리뷰트 - interfa
<class 'str'> 100
ce, _internal, __private\n"
   ]
  },
  {
   "attachments": {
    "9391263b-51eb-469f-8e2b-417d62e8e
<class 'str'> 100
f98.png": {
     "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjsAAAFoCAYAAACxJDqfAAAgAElEQVR4Ae2di5XctrJFb
<class 'str'> 100
wqOQSk4B4egGJSCMnAGysARKAIn4ASUgXLQW1vPxzpTKoAgm5zpbh2s1RckUKjPBghUs8dX//uWEgIhEAIhEAIhEAJPTOB/TxxbQ
<class 'str'> 100
guBEAiBEAiBEAiBb0l2sghCIARCIARCIASemkCSnaee3gQXAiEQAiEQAiGQZCdrIARCIARCIARC4KkJJNl56ulNcCEQAiEQAiEQA
<class 'str'> 100
kl2sgZCIARCIARCIASemsAlyc6ff/757X//+9/3j+jp/o8//lDT7vrvv//+Ty/XlN9+++1725beDx8+fJejTrmdwJcvX77zhP8//
<class 'str'> 100
/xzu8JoCIEQCIEQCIGLCOxKdpSwdDWH3l9//fXdzSPJzvv37/9LZKQfnV66ZEeys2QHv5BD39evX13lKdeKd+bDyBBj8OsREwbF/
<class 'str'> 100
fvvv4/CS3sIhEAIhEAIvDmB05Idkgkd9joEaVPZSkquSnZIbkgmsI9fo8Kbio8fP37j4Jav1MSkJG40VvEq/pFcbffkbe/Yqust7
<class 'str'> 100
lfZvoVvsRkCIRACIRACIvAjG1HLztoPbJIFig5/kgUVJRC3HOpui2vKll79fDV7q6M3P9LV1e/evRu+fVG8e2PzePaOFdejtdsWy
<class 'str'> 100
yO6FDvMSBhTQiAEQiAEQuDeCPzIRg565oedforxNqlVAlEPdT90JeO1y7usDmjJupxs6u9KkMGnrniiQ0LEvX7qYrzHMvq5STKdD
<class 'str'> 100
51Nb+NNEnoVj/dded2xPGIPVpqD7u+h6IcLMkqGj9jJmBAIgRAIgRA4SuCmZMd/xvCDXoe/DkGvXQ6n/dB1Ob9W8uGySg4kV/Wim
<class 'str'> 100
8NV/d1bB0+GeHMjOxWmJ0Td36co3s6Hqute7juWR33TT5AkbbU4O+YiJQRCIARCIARem8BNp49+IuIQU/JBADr8lWh4vZoQcHAyz
<class 'str'> 100
pOL7oCW7k4vCUzV4YBH/ruMrj1x+vz5s5q/14q38+GF4B3ddCyPuucJTWWTNztHqWZcCIRACITAWQQOJzueKNSfJ3T4k2iozJISy
<class 'str'> 100
ajmwJQ8B6lKd0BLriYa/tam+id9XUKlvlq7Pt5keFG8+ICPetOBbyRrHoOP41r+f/r0qXZ9/xsYOMtPanTr58KfBnz79v3tFP5gV
<class 'str'> 100
7pV4xt2dF9rZ0i81Tb3nW1nM2Ld+Zq2EAiBEAiBEHgNAj+ykUVrHHZ+kHIA1qLDn8NURQerH6jqq7X0c7hTNNZrDm7vq3o9MeqSD
<class 'str'> 100
eKQPvxdKfKLN0ZeFK+SEun1uiZIGi+Z6gP+jfTR3iUdszHYISlZSXaQG9munBWH5Ef9kksdAiEQAiEQAq9N4Ec2smFZ3/R1OFOPv
<class 'str'> 100
sXr8EdGReO2DkM/jJWkaKzXW8mO+yBZ+UK9lQy5rK7xXT6ojdptcejLHj/hkAxqTE1oGNv1MU7Jg+tDr9prwuUJCn315yT3l2uPX
<class 'str'> 100
/5KhnmVX+pDP/6Pkjaxwb+UEAiBEAiBELgnAj+ykYlXHL46/Kg5THUIdsP88Fe/xs+Snfpmor416g7okV73ofO10yVfR7UOdGx6c
<class 'str'> 100
VtdkqFxNUFBh/xHh4onfNV3EkCNcVueVJGYbJVZ/P4zHHO/UhRjZbMyNjIhEAIhEAIhcCWBl6f2xBKHKYe13rZMRF+86ZCc3kiM3
<class 'str'> 100
gzUREcHOnZ14HYHtORqEuUJSE0Y8Ml1rcTEmNGB7rYUr9eevNSfn+S/Jzuy0yVH6O3GiG9NEN0Pv/b4Kx//myl88KTKdfi1fMa3l
<class 'str'> 100
BAIgRAIgRC4JwJ3cTJx2OqwpiYh8DcV/K0Mbd0BrYN/b7KDPo31RGM2OVt/s0N/Vzq/Jdf54ImD+rvaExv1r8Yy8wnfSNA0J+gm6
<class 'str'> 100
WHMqMhnxqSEQAiEQAiEwD0ROJTseKKgQ3a1rm8J/K0IB6W/ZfGEh77ugJbdmuy4rOt0+DrMR0mKy/LTkGzVt1OKYaTHfakJg3R6k
<class 'str'> 100
qLEQX2j+spkh9h5o6bY5MMWyzoPzjDXIRACIRACIfAWBF492fHDkINThyiJB0lULfoJiCSpSxo03vWiw5OT0R9SezJVk5Dqh//Rb
<class 'str'> 100
j3wPSHQT24+XjHga41R/nfJzih5ct26lh5PgNTX1R3LTo42WOKLbNS/CSJm9Y1Yj3SnPQRCIARCIASuJnAo2TnilA7DmpRwiNJWD
<class 'str'> 100
1C3oQSiO6BHehnPTy/0j5IGT4iQlR23zbXbRa4WT3ZIbGohPvwgoatF/nuy44lVTY7qeN174rYyxmPieqvM5D1prW/uYKr4kwhtU
<class 'str'> 100
U5/CIRACITAFQTePNnZE1R34CpZqEkUej1pGCVTnqiQjHBwK+lhTO3vEokqozc/6PEkxBMaxS3/vc+TMHzyBAL7yNaf0hiDrJIqj
<class 'str'> 100
0O2vHYb8lf9sISdYiUO/y+01C55xYh9sVMfuhUjdUoIhEAIhEAIvDaBVzt9dOB1Sclq0HuTHT/QPZmo9uiTf6Oag7we8tKj8cTmP
<class 'str'> 100
/e4rtHbJclU/2qSIDnVHUf8U8IjOa/rGxy9+XIZdKDb2/y6/kxGcqP+2gcf+qUvb3a0YlKHQAiEQAi8JoGnTnYAqbcO3c9PDprEi
<class 'str'> 100
MO4Jisc1Pw0Vd9Y+FhPdpBDj5IO9NVExscqUehkSE7w35MS6Rv5Qzu6ahzYqckOiU2VQ0YxeB/X9Q0QcSh29MMwJQRCIARCIATuj
<class 'str'> 100
cDTJzscwEo8ur+neesJUbJTE5G39mvFPkmR2HbJ2oqOyIRACIRACITA1QReLdnRoVj/1uTWAKW3+1lHuvWTELKjNyKSfc2aBOeRk
<class 'str'> 100
x291eGtT0oIhEAIhEAI3CuBV0t23hqAfs7q/q7kLXxTkkO99RPbW/i3ZVN/D0UCOfpbpi0d6Q+BEAiBEAiB1yDwyyQ7rwFzjw0lO
<class 'str'> 100
7wVSbKwh1xkQyAEQiAEQmAfgSQ7+3hFOgRCIARCIARC4MEIJNl5sAmLuyEQAiEQAiEQAvsIJNnZxyvSIRACIRACIRACD0Ygyc6DT
<class 'str'> 100
VjcDYEQCIEQCIEQ2Ecgyc4+XpEOgRAIgRAIgRB4MAJJdh5swuJuCIRACIRACITAPgJJdvbxinQIhEAIhEAIhMCDEUiy82ATFndDI
<class 'str'> 100
ARCIARCIAT2EUiys49XpEMgBEIgBEIgBB6MQJKdB5uwuBsCIRACIRACIbCPQJKdfbwiHQIhEAIhEAIh8GAEkuw82ITF3RAIgRAIg
<class 'str'> 100
RAIgX0Efplk548//vj2/v37fXQG0n///fc3/iHPM8qff/75Dd/OLviHn5SzbJylB5+IGX1dEV/9Y6lb9efPnzs1N7XV9TLzd8tQ5
<class 'str'> 100
eZzszX2qv4R4yvWYmV5S0yw+/Tp0y0qMjYEQuAXJHDOif0A4NhwtzZyDqV37959T2R+++23bx8+fPj29evXn6LTQfFThzXUA200p
<class 'str'> 100
h6EpuKmS7c/s0F8xEm8jCF+5Lsy09PJz9qYi5Gd2bjad0QPcXYfYlep62Vmp+pirr1UbshXGeSRq7pm9x8/fnQzb3Y9Y4NTlWV1d
<class 'str'> 100
BR3tz7g0bVXnbkPgRAIASfwkMkOm+fsEPA+Bbu14XLg//777/8dQl++fPl+T1tNeEaJi2xR44MfaKMxbNz4tlLwSUmJx6hr+lXc/
<class 'str'> 100
sgGcREfb7w0Fj+V6EmX6pEe3qzIh67uDidi7tpla7U+Sw++4LtKXS+32KncfG5kb29dde4df6b8LEHGTmV5i23YnbFubvEhY0MgB
<class 'str'> 100
B6PwI/d/fF8/++bsLuupMITDfpnG67G/PPPP67qe5LTbeSSfyFsNyQObMqu76+//vqeRJjY98s9h9aWXdftB+rIBu3EV5M5/Pbx0
<class 'str'> 100
jvTg/yeMksetpI6bPnnjJ+xSPjwSaWul5m/GjOqK7eO7WjsqL3qHMnVduc2u2ZdKAGuOuo9eljfo1JZSm5mv/bpeaad2FNCIARCY
<class 'str'> 100
A+BfSfUHs2vIMumx+bnRQmBNkf1jTZc+jnoRn/Pw98H8KbDi2x4m193iQ0/OeBDLXsOrS27rhsuYjCyQVyjv3/omIz0dPPgvnTXs
<class 'str'> 100
+RhT5yd7r1tJHuVRV0vnb+Kux7M3PvhX7n53Oz1VfJVp9pvrWFBogOPlWRHb/VG6wh/KstbfIQdsaeEQAiEwB4CLzOFPSPvQFaHj
<class 'str'> 100
buig1IHvfpmGy4b+2gD7fSpTbprrb+B8Tcm/Fykv7HAFz8guV8pW3Zdhx+o3cE4ensjHR3bTg/ynaz0jGpiZlxXFKfz6+TOasMP1
<class 'str'> 100
oDbq3O0esiK65FkR4mDr43ZtdbTWRywDwdsuv8z/ax15EmQRqWyrOsd7npm0IUPJNv+ZlS66R+tG8mkDoEQCIFKIMnOv39fM/spp
<class 'str'> 100
G7+OowrTO7ZuNms2by1KetnmbrJI49M197pntmt8viM/MiGdPkB7zrU79/uR77Sjr09hZjFp44TL3SufqqO1XslJ9UX/PN5mfnrt
<class 'str'> 100
tBTEyfaXJfPTR3rct535TVzjV38ImnpkozOPvPEGL39HCVf6B7FpeeF5EZrjTaYdZxoq3PV+Za2EAiBEHAC+04oH3kH19oQ3RUd0
<class 'str'> 100
tReZhtut6n62LrByobL6BqfSHS0iZNEqY3DoL7up290EEin6pFdccBP/4hBZ2Okq9qSDto7PWp3u/V6JIO+tywc6iQmHf+6Xrjf8
<class 'str'> 100
ldzXuUqN/g4VzGocmq/osZX3t4Ql+YLFp1fI/u8rRQ7rafujVBl6fp4JkZvhejDhhd8rXy9P9chEAIh0BH4pZIdberU2qSBwv0Zb
<class 'str'> 100
3Z0eOobqt4acIjQxgFTvznvOeB0oHQTWduISQdXZ0O68Kkr6lcsyHR61I69PQX+b3lo6W0Eh2nHoB7QK/7ydoL5RZ/4wYVPXW+aG
<class 'str'> 100
2c24usyt1wzlyQj+IlP+EpCwTqlT4kH7STsPBMdG3zQz06+PpBnraPfx1WWHsOsDx51XXH/luvGfc91CITA4xDYd0JdEBebJhuYf
<class 'str'> 100
1Y3s24z1CFTD5PZpsoGPbLZ6VOb42Bz5+CserDLIaKihEjJFfLIrJTO7mgcPMWgs6FETDJVD2PQ4aXTQ38n6+O6a2JmnIr88XVw5
<class 'str'> 100
Np1SrfXxIttdPu8uAzXyPi8VH+rPEkEOuubCOQqN+Q67lWu2rjlHv9Y54oD3qNCH8kgsozxQnKj9k4HbfQ7W+75dEUJVtfH3kDi5
<class 'str'> 100
aWuia359rG5DoEQ+HUJvDzNHowDGx2bnxcOke4wmW24fBMdbcbYqBu+bLhdDpN60LFZd28OkNUbgD0HXGfXffBrZzCyQVz0dQUec
<class 'str'> 100
PEy0kN7nQcf112jf2S7kz+rTXPdHdRuo8Y/81eJDgmC3oq4rsrN58blSIDp2/PpkibXefY1yQlr2t/obNmAHZ+u8CWBdci8aE5o0
<class 'str'> 100
5rSlwKNhc1brBvZTx0CIfCYBF5mCg8WgzZEd1sJQT0EZhuuxmizlT5txHVzlbzkuprDgE286qyy6B4dBFV2xa7G+IE6skG7ki6No
<class 'str'> 100
5Ydai8zPdjbU4gZfY9elOiQ2FKYb+addpXKzedGMrN6r/xM11v0Mdc1cXY/eFbgBzdi5YN8XX+Moe8Z1o3Hn+sQCIHrCew7oa73Z
<class 'str'> 100
5cFNj02Py98u6aN2hONWbLDeG222mDZgPkG272ZQabadR/2XNeDcDZWdknCtgr+KZaRDfQoRn1TZwyHjg5vtzPS082Dj+uuZ8mO9
<class 'str'> 100
BHDyqd+++/sdW34sKIfGZiIp3RpreGvFyVA9FMqN/RVXT6+Xu+Vr+M9iViNt8rBalSIl+TE7XBNmyd9o/HevhUr/ZW3j891CIRAC
<class 'str'> 100
HQEXmYKncQdttWN2O+V1PhBRghqn4XDJsqbDvSxWfPKvkssOKiQmZV6wI1kV+UYT0Ii/zxmv9ZBQJsO1JkN4lOixxj065CuPo/06
<class 'str'> 100
G2G+9Fd1+RTvlY7e+6Z1y4x26NjRZZ43F/mgjUySrQ45OmHb+WGLs3Nqu098is6XQaGHpv3za6JjbGsGeJVwswYrmmjr/vCMNK7x
<class 'str'> 100
abOw0hP2kMgBELACcxPbJd88OuVZGc1xDOTnVWbe+X80KiH7V5dkj9LD/qOHrDyRTV63iLZkf2VunLzuVkZv1d+RafLHJ0LkmIld
<class 'str'> 100
K7Pr0mISHjqz1h6hoht9aMxRxIz9ynXIRACvx6BJDsH5lyb7mxoPeBmslf0+QF5li9n6SHe2QGrtyarh+Do7cqZXPHl6CFbufnc8
<class 'str'> 100
LZrNc6Z3FHftuZixpA55LNV8I2E54xyyzycYT86QiAEHpNAkp0D85Zk5wC0MmSW7OhvYcqQN7295ZCdJTtvGtS/xmdzMfPvljc7M
<class 'str'> 100

In [ ]:
f = open(examfile, 'r')
line = f.readline()
print(line)
f.close()

### 내용 추가하기

`append` 모드는 파일이 있으면 뒤에 내용을 추가, `<MODE>`를 `a`로 제시하면 파일의 끝에 내용을 추가할 수 있다.

In [ ]:
f = open('testfile.txt', 'a')
for i in range(11, 20):
    data = "%d번째 줄입니다.\n" % i
    f.write(data)
f.close()

### with ~ as
`with ~ as` 를 이용하면 파일 `close 작업을 자동으로 수행` -> 안전하게 시스템 자원을 활용
즉 close() 메서드를 명시하지 않아도, 파일을 다 사용후에 닫아 준다.

`split()` 를 사용해 파일을 불러와서 개행문자 구분한 리스트로 반환

In [35]:
with open("Q-sequence실습.ipynb", "rt", encoding="utf8") as f:
    lines = f.readlines()
len(lines)

120

In [36]:
type(lines)

list

In [37]:
lines[:10]

['{\n',
 ' "cells": [\n',
 '  {\n',
 '   "cell_type": "code",\n',
 '   "execution_count": null,\n',
 '   "id": "e730fa8e-1842-467d-9831-7d15570b5aca",\n',
 '   "metadata": {},\n',
 '   "outputs": [],\n',
 '   "source": []\n',
 '  },\n']

In [58]:
with open("Q-sequence실습.ipynb", "rt", encoding="utf8") as f:
    lines = f.readlines()
print("lines:", lines)

lines: ['{\n', ' "cells": [\n', '  {\n', '   "cell_type": "code",\n', '   "execution_count": null,\n', '   "id": "e730fa8e-1842-467d-9831-7d15570b5aca",\n', '   "metadata": {},\n', '   "outputs": [],\n', '   "source": []\n', '  },\n', '  {\n', '   "cell_type": "markdown",\n', '   "id": "63437bce-b594-4c32-b09a-405965a4d3e0",\n', '   "metadata": {},\n', '   "source": [\n', '    "## 연습) 전화번호를 \'-\'를 포함해 입력받아 \'-\' 제거해서 출력한다.\\n",\n', '    "\\n",\n', '    "```\\n",\n', '    "Q) 하이픈(-)을 포함한 휴대폰 번호를 입력하세요:  234-1234--4444\\n",\n', '    "23412344444\\n",\n', '    "```"\n', '   ]\n', '  },\n', '  {\n', '   "cell_type": "code",\n', '   "execution_count": null,\n', '   "id": "eda1b902-c2ad-4f3e-b762-7929bb5b2b9a",\n', '   "metadata": {},\n', '   "outputs": [],\n', '   "source": []\n', '  },\n', '  {\n', '   "cell_type": "markdown",\n', '   "id": "0149a832-2f60-4741-8921-40a1825c37ac",\n', '   "metadata": {},\n', '   "source": [\n', '    "## 연습) 전화번호 숫자만 입력받아 \'-\' 를 포함해 출력한다.\\n",\n', '    "\\n",\n', '    "```\\n",\n', '    "Q) 휴대폰 번호 숫자만 입력하세요:  23412344444\\n",\n', '    "234-1234-4444\\n",\n', '    "```"\n', '   ]\n', '  },\n', '  {\n', '   "cell_type": "code",\n', '   "execution_count": null,\n', '   "id": "42cc23f4-31f6-4fe6-abe9-ea438f6b60d9",\n', '   "metadata": {},\n', '   "outputs": [],\n', '   "source": []\n', '  },\n', '  {\n', '   "cell_type": "markdown",\n', '   "id": "c8ab0ef6-9348-402a-b41f-045f727c0e17",\n', '   "metadata": {},\n', '   "source": [\n', '    "## 연습) 다음 리스트는 어느 회의실의 좌석 배치이다. 1은 남성, 2는 여성 그리고 0은 빈 좌석이다. 이 데이터에서 남성/여성의 좌석수를  for / while 문으로 세어서 출력하시오.\\n",\n', '    "\\n",\n', '    "```\\n",\n', '    "seats = [[0, 0, 2, 1, 0, 0, 0, 0, 0 ],\\\\\\n",\n', '    "         [2, 1, 0, 1, 2, 1, 2, 1, 0 ],\\\\\\n",\n', '    "         [0, 2, 1, 1, 1, 2, 2, 0, 0 ],\\\\\\n",\n', '    "         [0, 0, 2, 2, 2, 1, 0, 2, 0 ],\\\\\\n",\n', '    "         [1, 1, 1, 0, 0, 1, 0, 2, 1 ],\\\\\\n",\n', '    "         [1, 0, 0, 2, 0, 1, 2, 1, 0 ],\\\\\\n",\n', '    "         [2, 2, 0, 2, 1, 0, 1, 1, 0 ],\\\\\\n",\n', '    "         [0, 0, 0, 1, 1, 0, 0, 0, 0 ],\\\\\\n",\n', '    "         [0, 0, 0, 0, 2, 2, 2, 0, 0 ]]\\n",\n', '    "```"\n', '   ]\n', '  },\n', '  {\n', '   "cell_type": "code",\n', '   "execution_count": null,\n', '   "id": "652266a6-852d-4a55-84e4-f0d00de64353",\n', '   "metadata": {},\n', '   "outputs": [],\n', '   "source": []\n', '  },\n', '  {\n', '   "cell_type": "markdown",\n', '   "id": "e5baef44-2e4d-4b98-ac1d-b90b1bf355e4",\n', '   "metadata": {},\n', '   "source": [\n', '    "## \\"연습\\" 다음 같은 자료를 dict 로 선언하고  각 자료를 Enumerate 하게 탐색해 보시오\\n",\n', '    "```\\n",\n', '    "    \\"홍길동\\": \\"010-1234-5678\\",\\n",\n', '    "    \\"임꺽정\\": \\"010-9876-5432\\",\\n",\n', '    "   \\"장길산\\": \\"010-5678-0987\\"\\n",\n', '    "```\\n",\n', '    "\\n",\n', '    " - keys()\\n",\n', '    " - items()\\n",\n', '    " - enumerate()"\n', '   ]\n', '  }\n', ' ],\n', ' "metadata": {\n', '  "kernelspec": {\n', '   "display_name": "Python 3 (ipykernel)",\n', '   "language": "python",\n', '   "name": "python3"\n', '  },\n', '  "language_info": {\n', '   "codemirror_mode": {\n', '    "name": "ipython",\n', '    "version": 3\n', '   },\n', '   "file_extension": ".py",\n', '   "mimetype": "text/x-python",\n', '   "name": "python",\n', '   "nbconvert_exporter": "python",\n', '   "pygments_lexer": "ipython3",\n', '   "version": "3.10.6"\n', '  }\n', ' },\n', ' "nbformat": 4,\n', ' "nbformat_minor": 5\n', '}\n']

In [59]:
len(lines)

120

In [60]:
# 루프를 돌려 출력
for line in lines:
    print(line.strip()) # \n과 같은 특수문자, 공백문자 제거 후 한줄씩 출력함

{
"cells": [
{
"cell_type": "code",
"execution_count": null,
"id": "e730fa8e-1842-467d-9831-7d15570b5aca",
"metadata": {},
"outputs": [],
"source": []
},
{
"cell_type": "markdown",
"id": "63437bce-b594-4c32-b09a-405965a4d3e0",
"metadata": {},
"source": [
"## 연습) 전화번호를 '-'를 포함해 입력받아 '-' 제거해서 출력한다.\n",
"\n",
"```\n",
"Q) 하이픈(-)을 포함한 휴대폰 번호를 입력하세요:  234-1234--4444\n",
"23412344444\n",
"```"
]
},
{
"cell_type": "code",
"execution_count": null,
"id": "eda1b902-c2ad-4f3e-b762-7929bb5b2b9a",
"metadata": {},
"outputs": [],
"source": []
},
{
"cell_type": "markdown",
"id": "0149a832-2f60-4741-8921-40a1825c37ac",
"metadata": {},
"source": [
"## 연습) 전화번호 숫자만 입력받아 '-' 를 포함해 출력한다.\n",
"\n",
"```\n",
"Q) 휴대폰 번호 숫자만 입력하세요:  23412344444\n",
"234-1234-4444\n",
"```"
]
},
{
"cell_type": "code",
"execution_count": null,
"id": "42cc23f4-31f6-4fe6-abe9-ea438f6b60d9",
"metadata": {},
"outputs": [],
"source": []
},
{
"cell_type": "markdown",
"id": "c8ab0ef6-9348-402a-b41f-045f727c0e17",
"metadata": {},
"source": [
"## 연습) 다음 리스트는 어느 회의실의 좌석 배치이다. 1은 남성, 2는 여성 그리고 0은 빈 좌석이다. 이 데이터에서 남성/여성의 좌석수를  for / while 문으로 세어서 출력하시오.\n",
"\n",
"```\n",
"seats = [[0, 0, 2, 1, 0, 0, 0, 0, 0 ],\\\n",
"         [2, 1, 0, 1, 2, 1, 2, 1, 0 ],\\\n",
"         [0, 2, 1, 1, 1, 2, 2, 0, 0 ],\\\n",
"         [0, 0, 2, 2, 2, 1, 0, 2, 0 ],\\\n",
"         [1, 1, 1, 0, 0, 1, 0, 2, 1 ],\\\n",
"         [1, 0, 0, 2, 0, 1, 2, 1, 0 ],\\\n",
"         [2, 2, 0, 2, 1, 0, 1, 1, 0 ],\\\n",
"         [0, 0, 0, 1, 1, 0, 0, 0, 0 ],\\\n",
"         [0, 0, 0, 0, 2, 2, 2, 0, 0 ]]\n",
"```"
]
},
{
"cell_type": "code",
"execution_count": null,
"id": "652266a6-852d-4a55-84e4-f0d00de64353",
"metadata": {},
"outputs": [],
"source": []
},
{
"cell_type": "markdown",
"id": "e5baef44-2e4d-4b98-ac1d-b90b1bf355e4",
"metadata": {},
"source": [
"## \"연습\" 다음 같은 자료를 dict 로 선언하고  각 자료를 Enumerate 하게 탐색해 보시오\n",
"```\n",
"    \"홍길동\": \"010-1234-5678\",\n",
"    \"임꺽정\": \"010-9876-5432\",\n",
"   \"장길산\": \"010-5678-0987\"\n",
"```\n",
"\n",
" - keys()\n",
" - items()\n",
" - enumerate()"
]
}
],
"metadata": {
"kernelspec": {
"display_name": "Python 3 (ipykernel)",
"language": "python",
"name": "python3"
},
"language_info": {
"codemirror_mode": {
"name": "ipython",
"version": 3
},
"file_extension": ".py",
"mimetype": "text/x-python",
"name": "python",
"nbconvert_exporter": "python",
"pygments_lexer": "ipython3",
"version": "3.10.6"
}
},
"nbformat": 4,
"nbformat_minor": 5
}

### 쓰기 모드

In [ ]:
# # 파일 쓰기모드로 한 줄씩 쓰기
# f = open( './samples/testwrite.txt', 'w')
# for i in range(1, 11):
#     data = "%d번째 줄입니다.\n" % i
#     f.write(data)
# f.close()

쓰기 모드에서 with 를 곁들여서 쓸 수 있다.

In [38]:
# 윈도우..한글 문자코드가 있으면.. windows 저장시: CP949 / euc-kr

with open('testwrite.txt', 'w') as f: # w -> wt(기본이 텍스트파일임)
    for i in range(1, 10):
        data = '%d번째 줄입니다.\n' % i
        f.write(data) # 이거 무슨 기능임 > 쓰는 기능임

In [39]:
# 윈도우..한글 문자코드가 있으면.. windows 저장시: CP949 / euc-kr

with open('testwrite.txt', 'w', encoding='utf8') as f: # 얘도 되넹.. / utf8로 인코딩하면 읽을때도 얘로.. cp949로 하면 얘로 이렇게 하는거 같음
    for i in range(1, 10):
        data = '%d번째 줄입니다.\n' % i
        f.write(data)

In [41]:
with open("testwrite.txt", "r", encoding="cp949") as f:
    lines = f.readlines()
print("lines:", lines)

UnicodeDecodeError: 'cp949' codec can't decode byte 0xeb in position 14: illegal multibyte sequence

In [40]:
with open("testwrite.txt", "r", encoding="utf8") as f:
    lines = f.readlines()
print("lines:", lines)

lines: ['1번째 줄입니다.\n', '2번째 줄입니다.\n', '3번째 줄입니다.\n', '4번째 줄입니다.\n', '5번째 줄입니다.\n', '6번째 줄입니다.\n', '7번째 줄입니다.\n', '8번째 줄입니다.\n', '9번째 줄입니다.\n']

### 리스트로 반환받기

보통 작은 파일을 다룰 때 리스트를 사용하기 좋다.

In [ ]:
address = []
with open('address.txt') as file:
    for line in file: 
        line = line.strip() #or some other preprocessing
        address.append(line) #storing everything in memory

### 파일 실습

- 참고자료
- https://wikidocs.net/15102

#### 문제 1

어떤 파일에 1부터 30까지의 숫자 중 홀수를 각 라인 단위로 
파일에 입력하는 프로그램을 작성하세요.
(생성되는 파일의 이름은 odd_number.txt입니다.)

In [67]:
with open("odd_number.txt", "w") as f:
    for i in range(1,31):
        if i % 2 != 0:
            data = '%d' %i # print(i)하면 파일에 저장되지 않고 그냥 i출력만 되고 끝
            f.write(data)

In [71]:
with open("odd_number.txt", "r") as f:
    lines = f.readlines()
print(lines)

['1357911131517192123252729']

In [74]:
with open("odd_number1.txt", "w") as f:
    for i in range(1,31):
        if i % 2 != 0:
            data = '%d\n' %i # 똑같넹.. >> 안똑같아!!
            f.write(data)

In [75]:
with open("odd_number1.txt", "r") as f:
    lines = f.readlines()
print(lines)

['1\n', '3\n', '5\n', '7\n', '9\n', '11\n', '13\n', '15\n', '17\n', '19\n', '21\n', '23\n', '25\n', '27\n', '29\n']

In [76]:
with open("odd_number2.txt", "w") as f:
    for i in range(1,31):
        if i % 2 != 0:
            data = '%d\n' %i 
            f.write(data)

In [77]:
# 루프를 돌려 출력
with open("odd_number1.txt", "r") as f:
    for line in lines:
        print(line.strip()) # \n과 같은 특수문자, 공백문자 제거 후 한줄씩 출력함

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29

In [80]:
with open("odd_number정답.txt", 'w') as f:
    for i in range(1,31):
        if i % 2 == 1:
            f.write("%d\n" % i)

In [81]:
# 결과
with open("odd_number정답.txt", "r") as f:
    read = f.read()
    print(read)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29

#### 문제 2

어떤 파일에 1부터 30까지의 숫자 중 짝수를 각 라인 단위로 파일에 
입력하는 프로그램을 작성하세요.
(생성되는 파일의 이름은 even_number.txt입니다.)

In [83]:
with open("even_number.txt", 'w') as f:
    for i in range(1,31):
        if i % 2 == 0:
            f.write("%d\n" % i)
# 결과
with open("even_number.txt", "r") as f:
    read = f.read()
    print(read)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30

#### 문제3

현재 사용하는 `1-05Sequence_0.ipynb` 파일을 읽어 파일에 있는 단어의 개수를 세는 프로그램을 작성하시오.

In [63]:
with open("Q-sequence실습.ipynb", "r", encoding="utf8") as f:
    text = f.read()
    word = text.split()
    # print(len(word))
    print(word)

['{', '"cells":', '[', '{', '"cell_type":', '"code",', '"execution_count":', 'null,', '"id":', '"e730fa8e-1842-467d-9831-7d15570b5aca",', '"metadata":', '{},', '"outputs":', '[],', '"source":', '[]', '},', '{', '"cell_type":', '"markdown",', '"id":', '"63437bce-b594-4c32-b09a-405965a4d3e0",', '"metadata":', '{},', '"source":', '[', '"##', '연습)', '전화번호를', "'-'를", '포함해', '입력받아', "'-'", '제거해서', '출력한다.\\n",', '"\\n",', '"```\\n",', '"Q)', '하이픈(-)을', '포함한', '휴대폰', '번호를', '입력하세요:', '234-1234--4444\\n",', '"23412344444\\n",', '"```"', ']', '},', '{', '"cell_type":', '"code",', '"execution_count":', 'null,', '"id":', '"eda1b902-c2ad-4f3e-b762-7929bb5b2b9a",', '"metadata":', '{},', '"outputs":', '[],', '"source":', '[]', '},', '{', '"cell_type":', '"markdown",', '"id":', '"0149a832-2f60-4741-8921-40a1825c37ac",', '"metadata":', '{},', '"source":', '[', '"##', '연습)', '전화번호', '숫자만', '입력받아', "'-'", '를', '포함해', '출력한다.\\n",', '"\\n",', '"```\\n",', '"Q)', '휴대폰', '번호', '숫자만', '입력하세요:', '23412344444\\n",', '"234-1234-4444\\n",', '"```"', ']', '},', '{', '"cell_type":', '"code",', '"execution_count":', 'null,', '"id":', '"42cc23f4-31f6-4fe6-abe9-ea438f6b60d9",', '"metadata":', '{},', '"outputs":', '[],', '"source":', '[]', '},', '{', '"cell_type":', '"markdown",', '"id":', '"c8ab0ef6-9348-402a-b41f-045f727c0e17",', '"metadata":', '{},', '"source":', '[', '"##', '연습)', '다음', '리스트는', '어느', '회의실의', '좌석', '배치이다.', '1은', '남성,', '2는', '여성', '그리고', '0은', '빈', '좌석이다.', '이', '데이터에서', '남성/여성의', '좌석수를', 'for', '/', 'while', '문으로', '세어서', '출력하시오.\\n",', '"\\n",', '"```\\n",', '"seats', '=', '[[0,', '0,', '2,', '1,', '0,', '0,', '0,', '0,', '0', '],\\\\\\n",', '"', '[2,', '1,', '0,', '1,', '2,', '1,', '2,', '1,', '0', '],\\\\\\n",', '"', '[0,', '2,', '1,', '1,', '1,', '2,', '2,', '0,', '0', '],\\\\\\n",', '"', '[0,', '0,', '2,', '2,', '2,', '1,', '0,', '2,', '0', '],\\\\\\n",', '"', '[1,', '1,', '1,', '0,', '0,', '1,', '0,', '2,', '1', '],\\\\\\n",', '"', '[1,', '0,', '0,', '2,', '0,', '1,', '2,', '1,', '0', '],\\\\\\n",', '"', '[2,', '2,', '0,', '2,', '1,', '0,', '1,', '1,', '0', '],\\\\\\n",', '"', '[0,', '0,', '0,', '1,', '1,', '0,', '0,', '0,', '0', '],\\\\\\n",', '"', '[0,', '0,', '0,', '0,', '2,', '2,', '2,', '0,', '0', ']]\\n",', '"```"', ']', '},', '{', '"cell_type":', '"code",', '"execution_count":', 'null,', '"id":', '"652266a6-852d-4a55-84e4-f0d00de64353",', '"metadata":', '{},', '"outputs":', '[],', '"source":', '[]', '},', '{', '"cell_type":', '"markdown",', '"id":', '"e5baef44-2e4d-4b98-ac1d-b90b1bf355e4",', '"metadata":', '{},', '"source":', '[', '"##', '\\"연습\\"', '다음', '같은', '자료를', 'dict', '로', '선언하고', '각', '자료를', 'Enumerate', '하게', '탐색해', '보시오\\n",', '"```\\n",', '"', '\\"홍길동\\":', '\\"010-1234-5678\\",\\n",', '"', '\\"임꺽정\\":', '\\"010-9876-5432\\",\\n",', '"', '\\"장길산\\":', '\\"010-5678-0987\\"\\n",', '"```\\n",', '"\\n",', '"', '-', 'keys()\\n",', '"', '-', 'items()\\n",', '"', '-', 'enumerate()"', ']', '}', '],', '"metadata":', '{', '"kernelspec":', '{', '"display_name":', '"Python', '3', '(ipykernel)",', '"language":', '"python",', '"name":', '"python3"', '},', '"language_info":', '{', '"codemirror_mode":', '{', '"name":', '"ipython",', '"version":', '3', '},', '"file_extension":', '".py",', '"mimetype":', '"text/x-python",', '"name":', '"python",', '"nbconvert_exporter":', '"python",', '"pygments_lexer":', '"ipython3",', '"version":', '"3.10.6"', '}', '},', '"nbformat":', '4,', '"nbformat_minor":', '5', '}']

In [49]:
# count_word 프로그램: 원하는 파일의 단어 개수를 세는 프로그램

with open("Count_Word.ipynb", "w", encoding="utf8") as file: # 근데 Count_Word.ipynb 파일은 안 열림..(폴더에서 직접 클릭해서 열려면..)......?????
    open_file = input("파일의 이름을 입력하세요:")
    with open("%s" % open_file, "r", encoding="utf8") as f:
        text = f.read()
        word = text.split()
        print(len(word))

파일의 이름을 입력하세요: Q-sequence실습.ipynb

348

In [90]:
# 아무것도 안뜸.. 이거 사용하려면 어케함.. 모듈 사용처럼 import를 해야되는건가....흐음..................???

with open("Count_Word.ipynb", "r", encoding="utf8") as file:
    read = file.read()
    print(read)

- 외부의 자원에서 ...parsing..파싱...

In [48]:
# 강사님

#파일 읽기

#readines()로 모두 읽기
    
# 리스트 크기 만큼 반복
    # 문자열을 ' ' 분리 -> split
    # 결과를 len() -> ++sum

with open("Q-sequence실습.ipynb", "r", encoding='utf8') as f:
    line = f.readlines()
    count = 0
    for i in range(len(line)):
        text = line[i].split(' ') # 여기가 이상한듯... 이미 리스트인데 이렇게 나누는게 의미가 있나.? (783) >> 연결시키고 공백인건 count에 넣으면 안되는 듯!
        # text = line[i].strip() # 얘도...다름 결과가..(2316)
        count += len(text)
    print(count)

783

In [62]:
# 강사님

#파일 읽기

#readines()로 모두 읽기
    
# 리스트 크기 만큼 반복
    # 문자열을 ' ' 분리 -> split
    # 결과를 len() -> ++sum

with open("Q-sequence실습.ipynb", "r", encoding='utf8') as f:
    line = f.readlines()
    count = 0
    for i in range(len(line)):
        text = line[i]
        # print(text)
        word = []
        for k in range(len(text)):
            if text[k] != '':
                word.append(text[k]) 
        count += len(word) # 들여쓰기 중요
    print(count)

2795

In [1]:
# 정답 - 아닌듯..print(result)해보면 단어가 아니라 문자임.

result = []
with open("Q-sequence실습.ipynb", "r", encoding='utf8') as f:
    for line in f.readlines():
        word_list = list(line)
        # print(word_list)
        for _ in range(len(word_list)):
            result.append(word_list.pop())
# print(result)
print("파일의 단어수 {}개".format(len(result)))

파일의 단어수 2795개

---

### 텍스트파일 encoding

- Linux: Unicoe
- Windows: CP949

In [65]:
with open('text_cp949.txt', 'w', encoding='cp949') as f: # 안됨...
    for i in range(1, 10):
        data = f'{i} 번째 줄입니다.\n'
        f.write(data)

In [71]:
with open('text_utf8.txt', 'w', encoding='utf8') as f:
    for i in range(1, 10):
        data = f'{i} 번째 줄입니다.\n'
        f.write(data)

cp949 바로 읽기

In [67]:
with open("text_cp949.txt", "r") as f:
    lines = f.readlines()

print("lines:", lines)

lines: ['1 번째 줄입니다.\n', '2 번째 줄입니다.\n', '3 번째 줄입니다.\n', '4 번째 줄입니다.\n', '5 번째 줄입니다.\n', '6 번째 줄입니다.\n', '7 번째 줄입니다.\n', '8 번째 줄입니다.\n', '9 번째 줄입니다.\n']

In [68]:
with open("text_cp949.txt", "r", encoding='cp949') as f:
    lines = f.readlines()

print("lines:", lines)

lines: ['1 번째 줄입니다.\n', '2 번째 줄입니다.\n', '3 번째 줄입니다.\n', '4 번째 줄입니다.\n', '5 번째 줄입니다.\n', '6 번째 줄입니다.\n', '7 번째 줄입니다.\n', '8 번째 줄입니다.\n', '9 번째 줄입니다.\n']

utf8 바로 읽기

In [72]:
with open("text_utf8.txt", "r") as f:
    lines = f.readlines()

print("lines:", lines)

UnicodeDecodeError: 'cp949' codec can't decode byte 0xeb in position 15: illegal multibyte sequence

In [73]:
with open("text_utf8.txt", "r", encoding='cp949') as f:
    lines = f.readlines()

print("lines:", lines)

UnicodeDecodeError: 'cp949' codec can't decode byte 0xeb in position 15: illegal multibyte sequence

## binary mode

바이너리 파일은 바이너리 모드로 작성해서 사용해야 한다.

In [ ]:
"""
바이너리 파일 생성
"""
print("====== binary file =====")
f = open("test.bin", "wb")

for i in range(0, 256):
    data = i.to_bytes(1, 'little')
    f.write(data)
f.close()

In [77]:
a = 1
a.to_bytes(1, 'little') # little endian

b'\x01'

- little endian big endian (비트도..순서o 순서에 따라 크기, 값 !=) / os 표준을 만들때 ..little endian이 디폴트값

In [78]:
# with
print("====== with binary file =====")
with open("test.bin", "wb") as f: # wb -> 바이너리 형태로 저장됨

    for i in range(0, 256):
        data = i.to_bytes(1, 'little')
        f.write(data)

In [78]:
with open("test.bin", "rb") as f:
    print("{0}".format(f.read()).encode()) # 문자열화가 된걸 문자코드로 변환해줌
#     print(f'{f.read()}'.encode()) # a byte string

====== with binary file =====
b'b\'\\x00\\x01\\x02\\x03\\x04\\x05\\x06\\x07\\x08\\t\\n\\x0b\\x0c\\r\\x0e\\x0f\\x10\\x11\\x12\\x13\\x14\\x15\\x16\\x17\\x18\\x19\\x1a\\x1b\\x1c\\x1d\\x1e\\x1f !"#$%&\\\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\\x7f\\x80\\x81\\x82\\x83\\x84\\x85\\x86\\x87\\x88\\x89\\x8a\\x8b\\x8c\\x8d\\x8e\\x8f\\x90\\x91\\x92\\x93\\x94\\x95\\x96\\x97\\x98\\x99\\x9a\\x9b\\x9c\\x9d\\x9e\\x9f\\xa0\\xa1\\xa2\\xa3\\xa4\\xa5\\xa6\\xa7\\xa8\\xa9\\xaa\\xab\\xac\\xad\\xae\\xaf\\xb0\\xb1\\xb2\\xb3\\xb4\\xb5\\xb6\\xb7\\xb8\\xb9\\xba\\xbb\\xbc\\xbd\\xbe\\xbf\\xc0\\xc1\\xc2\\xc3\\xc4\\xc5\\xc6\\xc7\\xc8\\xc9\\xca\\xcb\\xcc\\xcd\\xce\\xcf\\xd0\\xd1\\xd2\\xd3\\xd4\\xd5\\xd6\\xd7\\xd8\\xd9\\xda\\xdb\\xdc\\xdd\\xde\\xdf\\xe0\\xe1\\xe2\\xe3\\xe4\\xe5\\xe6\\xe7\\xe8\\xe9\\xea\\xeb\\xec\\xed\\xee\\xef\\xf0\\xf1\\xf2\\xf3\\xf4\\xf5\\xf6\\xf7\\xf8\\xf9\\xfa\\xfb\\xfc\\xfd\\xfe\\xff\''

#### 바이너리 파일 복사

바이너리 모드로 rose-flower.jpeg를 읽어 들여서, 바이너리 모드로 rose-flower-copy.jpeg로 저장해 보자.

In [ ]:
with open("rose-flower.jpeg", "rb") as f:
    data = f.read()

print("읽은 데이터:", data)

# 저장
with open("rose-flower-copy.jpeg", "wb") as f:
    f.write(data)

# 디렉토리!

In [79]:
import os

In [80]:
os.cpu_count()

20

In [81]:
os.environ # 딕셔너리 자료로 리턴이 됨. > 환경변수 내역

environ{'ALLUSERSPROFILE': 'C:\\ProgramData',
        'APPDATA': 'C:\\Users\\SBAuser\\AppData\\Roaming',
        'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
        'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
        'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
        'COMPUTERNAME': 'DESKTOP-2G1VRPT',
        'COMSPEC': 'C:\\windows\\system32\\cmd.exe',
        'CONFIGSETROOT': 'C:\\windows\\ConfigSetRoot',
        'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
        'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',
        'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
        'HOMEDRIVE': 'C:',
        'HOMEPATH': '\\Users\\SBAuser',
        'LOCALAPPDATA': 'C:\\Users\\SBAuser\\AppData\\Local',
        'LOGONSERVER': '\\\\DESKTOP-2G1VRPT',
        'NUMBER_OF_PROCESSORS': '20',
        'ONEDRIVE': 'C:\\Users\\SBAuser\\OneDrive',
        'OS': 'Windows_NT',
        'PATH': 'C:\\Users\\SBAuser\\.venv\\Second_Day\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Users\\SBAuser\\.pyenv\\pyenv-win\\bin;C:\\Users\\SBAuser\\.pyenv\\pyenv-win\\shims;C:\\Users\\SBAuser\\AppData\\Local\\Microsoft\\WindowsApps;',
        'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL',
        'PROCESSOR_ARCHITECTURE': 'AMD64',
        'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 151 Stepping 2, GenuineIntel',
        'PROCESSOR_LEVEL': '6',
        'PROCESSOR_REVISION': '9702',
        'PROGRAMDATA': 'C:\\ProgramData',
        'PROGRAMFILES': 'C:\\Program Files',
        'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
        'PROGRAMW6432': 'C:\\Program Files',
        'PSMODULEPATH': 'C:\\Users\\SBAuser\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
        'PUBLIC': 'C:\\Users\\Public',
        'PYENV': 'C:\\Users\\SBAuser\\.pyenv\\pyenv-win\\',
        'PYENV_HOME': 'C:\\Users\\SBAuser\\.pyenv\\pyenv-win\\',
        'PYENV_ROOT': 'C:\\Users\\SBAuser\\.pyenv\\pyenv-win\\',
        'SESSIONNAME': 'Console',
        'SYSTEMDRIVE': 'C:',
        'SYSTEMROOT': 'C:\\windows',
        'TEMP': 'C:\\Users\\SBAuser\\AppData\\Local\\Temp',
        'TMP': 'C:\\Users\\SBAuser\\AppData\\Local\\Temp',
        'USERDOMAIN': 'DESKTOP-2G1VRPT',
        'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-2G1VRPT',
        'USERNAME': 'SBAuser',
        'USERPROFILE': 'C:\\Users\\SBAuser',
        'VIRTUAL_ENV': 'C:\\Users\\SBAuser\\.venv\\Second_Day',
        'WINDIR': 'C:\\windows',
        'ZES_ENABLE_SYSMAN': '1',
        '_OLD_VIRTUAL_PATH': 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Users\\SBAuser\\.pyenv\\pyenv-win\\bin;C:\\Users\\SBAuser\\.pyenv\\pyenv-win\\shims;C:\\Users\\SBAuser\\AppData\\Local\\Microsoft\\WindowsApps;',
        'JPY_SESSION_NAME': 'week2/8585bcd9-79dc-4c11-9e64-2c50e0d3e119',
        'JPY_INTERRUPT_EVENT': '2172',
        'IPY_INTERRUPT_EVENT': '2172',
        'JPY_PARENT_PID': '3100',
        'TERM': 'xterm-color',
        'CLICOLOR': '1',
        'PAGER': 'cat',
        'GIT_PAGER': 'cat',
        'MPLBACKEND': 'module://matplotlib_inline.backend_inline'}

In [82]:
os.environ['PATH'] # 딕셔너리니까 key로 접근!

'C:\\Users\\SBAuser\\.venv\\Second_Day\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Users\\SBAuser\\.pyenv\\pyenv-win\\bin;C:\\Users\\SBAuser\\.pyenv\\pyenv-win\\shims;C:\\Users\\SBAuser\\AppData\\Local\\Microsoft\\WindowsApps;'

In [85]:
os.environ['HOMEPATH']

'\\Users\\SBAuser'

In [86]:
os.listdir(os.environ['HOMEPATH']) # %ls-l과 똑같음

['.ipython',
 '.jupyter',
 '.pyenv',
 '.venv',
 '.vscode',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'install-pyenv-win.ps1',
 'Jupyter_Python',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{af909e20-bbae-11ec-b197-f74d6d44e5a0}.TM.blf',
 'NTUSER.DAT{af909e20-bbae-11ec-b197-f74d6d44e5a0}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{af909e20-bbae-11ec-b197-f74d6d44e5a0}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Templates',
 'Test',
 'Test2',
 'Videos',
 '시작 메뉴']

In [87]:
os.listdir(os.environ['HOMEPATH'] + '/Jupyter_Python')

['.ipynb_checkpoints',
 '1-01JupyterNotebook.ipynb',
 '1-02Basic_0.ipynb',
 '1-02Basic_1.ipynb',
 '1-02Basic_2.ipynb',
 '1-03Basic2.ipynb',
 '1-05Sequence_0.ipynb',
 'add.py',
 'sub1.md',
 'Untitled.ipynb',
 'week1',
 'week2',
 '__pycache__',
 '과제']

In [88]:
os.mkdir('Test11')

In [90]:
os.rename('Test11", "Test222")

SyntaxError: EOL while scanning string literal (2869204847.py, line 1)

In [91]:
os.rmdir('Test11')

In [92]:
import glob

In [93]:
files = glob.glob('*.ipynb')

In [94]:
files

['1-06Function.ipynb',
 '1-17File-0.ipynb',
 'Count_Word.ipynb',
 'Q-Guess_Number(random).ipynb',
 'Q-sequence실습.ipynb',
 'WEEK1-RE.ipynb']

In [95]:
files = glob.glob('*') # os.listdir 과 결과 =

In [96]:
files

['1-06Function.ipynb',
 '1-17File-0.ipynb',
 'Count_Word.ipynb',
 'even_number.txt',
 'odd_number.txt',
 'odd_number1.txt',
 'odd_number2.txt',
 'odd_number정답.txt',
 'Q-Guess_Number(random).ipynb',
 'Q-sequence실습.ipynb',
 'test.bin',
 'test.txt',
 'testwrite.txt',
 'text_cp949.txt',
 'text_utf8.txt',
 'WEEK1-RE.ipynb']

In [105]:
glob.glob('../*/**', recursive = False) # 서브디렉토리가지 나옴 / True여도 나오기 함.

['..\\week1\\1-01JupyterNotebook.ipynb',
 '..\\week1\\1-02Basic_0.ipynb',
 '..\\week1\\1-02Basic_1.ipynb',
 '..\\week1\\1-02Basic_2.ipynb',
 '..\\week1\\1-03Basic2.ipynb',
 '..\\week1\\1-05Sequence_0.ipynb',
 '..\\week1\\add.py',
 '..\\week1\\sub1.md',
 '..\\week1\\Untitled.ipynb',
 '..\\week2\\1-06Function.ipynb',
 '..\\week2\\1-17File-0.ipynb',
 '..\\week2\\Count_Word.ipynb',
 '..\\week2\\even_number.txt',
 '..\\week2\\odd_number.txt',
 '..\\week2\\odd_number1.txt',
 '..\\week2\\odd_number2.txt',
 '..\\week2\\odd_number정답.txt',
 '..\\week2\\Q-Guess_Number(random).ipynb',
 '..\\week2\\Q-sequence실습.ipynb',
 '..\\week2\\test.bin',
 '..\\week2\\test.txt',
 '..\\week2\\testwrite.txt',
 '..\\week2\\text_cp949.txt',
 '..\\week2\\text_utf8.txt',
 '..\\week2\\WEEK1-RE.ipynb',
 '..\\__pycache__\\add.cpython-39.pyc',
 '..\\과제\\20221110_김은경.ipynb',
 '..\\과제\\20221111_김은경.ipynb',
 '..\\과제\\20221114_김은경.ipynb',
 '..\\과제\\20221115_김은경.ipynb',
 '..\\과제\\Untitled.ipynb']

In [106]:
files = glob.glob('../*/**', recursive = False)

In [107]:
len(files)

31

In [109]:
for file in files[:30]:
    # print(file)
    if os.path.isdir(file): # 디렉토리만 리스트업 하겠다
        print(file)

In [110]:
for file in files[:30]:
    # print(file)
    if os.path.isfile(file): # 파일만 리스트업 하겠다
        print(file)

..\week1\1-01JupyterNotebook.ipynb
..\week1\1-02Basic_0.ipynb
..\week1\1-02Basic_1.ipynb
..\week1\1-02Basic_2.ipynb
..\week1\1-03Basic2.ipynb
..\week1\1-05Sequence_0.ipynb
..\week1\add.py
..\week1\sub1.md
..\week1\Untitled.ipynb
..\week2\1-06Function.ipynb
..\week2\1-17File-0.ipynb
..\week2\Count_Word.ipynb
..\week2\even_number.txt
..\week2\odd_number.txt
..\week2\odd_number1.txt
..\week2\odd_number2.txt
..\week2\odd_number정답.txt
..\week2\Q-Guess_Number(random).ipynb
..\week2\Q-sequence실습.ipynb
..\week2\test.bin
..\week2\test.txt
..\week2\testwrite.txt
..\week2\text_cp949.txt
..\week2\text_utf8.txt
..\week2\WEEK1-RE.ipynb
..\__pycache__\add.cpython-39.pyc
..\과제\20221110_김은경.ipynb
..\과제\20221111_김은경.ipynb
..\과제\20221114_김은경.ipynb
..\과제\20221115_김은경.ipynb